### ISSUE TITLE
fix(quay): Format date, size and Manifest information to be same as on the quay UI

### ISSUE THREAD

**Issue by fmenesesg** [janus-idp/backstage-plugins#100]
The "LAST MODIFIED" field is showing a full timestamp  "Thu, 23 Jun 2022 20:31:28 -0000" and should be like this "Jun 23, 2022, 4:31 PM" as the Quay interface show.

The SIZE is on bytes like this "1656016288" and should be MB or GB according to a calculation.

MANIFEST value should be a substring(0, 19) instead of the all value

**Comment by tumido** [comment]
Resolved via #101
