### ISSUE TITLE
keycloak-backend: only top level groups are synced from keycloak 23+

### ISSUE THREAD

**Issue by ikatlinsky** [janus-idp/backstage-plugins#1046]
### Describe the bug

Keycloak 23 introduced a breaking change for fetching the subgroups for groups - https://github.com/keycloak/keycloak/issues/22372. As a result, the current implementation of the keycloak-backend plugin syncs only top-level groups.

### Expected Behavior

keycloak-backend plugin should correctly sync all groups for keycloak 23+.

### What are the steps to reproduce this bug?

1. launch keycloak 23+
2. create a hierarchical groups structure with multiple groups
3. run sync from launched keycloak

### Versions of software used and environment

Keycloak: 23.0.3
keycloak-backen: 1.7.3

**Comment by schultzp2020** [comment]
Sadly we cannot support keycloak `>18` https://github.com/janus-idp/backstage-plugins/issues/47
