### ISSUE TITLE
App Topology - Integrate k8s plugin with topology plugin

### ISSUE THREAD

**Issue by divyanshiGupta** [janus-idp/backstage-plugins#105]
**Description:**
Based on the evaluation story - https://github.com/janus-idp/backstage-plugins/issues/91 integrate k8s plugin with topology plugin and use its api to get the entity's k8s resources from the associated cluster.

**Acceptance Criteria:**

- [x] Integrate k8s plugin with topology plugin
- [x] Use k8s plugin api to get the resources
- [x] Refactor data model/transform utils

**Comment by invincibleJai** [comment]
associated PR https://github.com/janus-idp/backstage-plugins/pull/104
