### ISSUE TITLE
UI Review of Quay UI plugin

### ISSUE THREAD

**Issue by serenamarie125** [janus-idp/backstage-plugins#108]
## Goal
Review the upstream [Quay UI plugin](https://github.com/janus-idp/backstage-plugins/tree/main/plugins/quay) (do we need a template for this?):

## Why
Review the UI and user experience associated with this UI plugin to identify gaps before milestone as well as add possible backlog items for the future.  

## Acceptance Criteria
- [x] Identify and add GH stories needed before this epic is considered "complete" from a UI/UX perspective for Milestone 01 (tag with appropriate milestone & include in #60 
- [x] Identify and add GH stories, considered as enhancements, from a UI/UX perspective, which can be accomplished before Milestone 01

**Comment by rtaniwa** [comment]
As discussed, review is complete. Marking this one as complete.
