### ISSUE TITLE
[kiali] Kiali Plugin not reach the backend correctly when you add a path

### ISSUE THREAD

**Issue by aljesusg** [janus-idp/backstage-plugins#1093]
### Describe the bug

The kiali-backend not let to add a full path in the url.
When you set in the pp-config the kiali provider url with a subpath kiali-backend ignore it.

The error is in L150 in kiali-backend/src/client/fetch.ts

```ts
requestInit.url = new URL(endpoint, this.KialiDetails.url).href;
```

the URL class ignore if you set a path in the url

### Expected Behavior

Query to **https://kiali-istio-system.apps-crc.testing/kiali/api/auth/info**

### What are the steps to reproduce this bug?

1. Add in app-config the kiali provider the url with a path (Ex: https://kiali-istio-system.apps-crc.testing/kiali)
2. Check that kiali is triying to reach **https://kiali-istio-system.apps-crc.testing/api/auth/info** instead
**https://kiali-istio-system.apps-crc.testing/kiali api/auth/info**

Please add **plugin/kiali** label and assign this one to @josunect

**Comment by josunect** [comment]
Can I get this assigned? Thanks
