### ISSUE TITLE
[Topology] Forbidden error on viewing pod logs

### ISSUE THREAD

**Issue by debsmita1** [janus-idp/backstage-plugins#1094]
**Description of the bug:**

Unable to view pod logs

**Test setup:**

Install and configure the Topology plugin

**Screenshot:**

![Screenshot 2024-01-19 at 8 39 51 PM](https://github.com/janus-idp/backstage-plugins/assets/22490998/76629167-c7e9-42a7-b3a7-3856a28bf53e)

**Comment by invincibleJai** [comment]
the issue is observed if RBAC is enabled and permission is not configured.

If RBAC is enabled, then add below permission to enable k8s

`p, role:default/rbac_admin, kubernetes.proxy, use, allow`
