### ISSUE TITLE
Enhance janus-idp/cli "new" command to include a working turbo.json and tsconfig.json

### ISSUE THREAD

**Issue by gashcrumb** [janus-idp/backstage-plugins#1105]
### What do you want to improve?

It'd be helpful if the janus-idp/cli new command also inlcuded working `turbo.json` and `tsconfig.json` files, as well as maybe include a `tsc` command and adds dynamic plugin support out of the box.  Maybe the latter two can be extra credit :-)

### What is the current behavior?

1)  Run `./packages/cli/bin/janus-cli new` to create a new plugin in `backstage-plugins`
2)  Add "tsc": "tsc" to the plugin's package.json's `scripts` section
3)  Run `yarn tsc` and observe errors.  
4)  Copy `turbo.json` and `tsconfig.json` from someone else's plugin and adapt.

### What will the new behavior be?

After running the `new` command the aforementioned files should be present and set up appropriately so that after creating a new plugin, `yarn tsc` and `yarn build` at the root should work and include the newly created plugin.

**Comment by davidfestal** [comment]
Maybe what you're looking for is already included into PR https://github.com/janus-idp/backstage-plugins/pull/782 ?

**Comment by tumido** [comment]
All of this is already part of #782 🙂

**Comment by gashcrumb** [comment]
That's excellent, thanks!  Will have a :eyes:
