### ISSUE TITLE
Update or remove support button on dynamic-plugins-info

### ISSUE THREAD

**Issue by gashcrumb** [janus-idp/backstage-plugins#1150]
[This PR](https://github.com/janus-idp/backstage-plugins/pull/1138) adds the dynamic-plugins-info button, however the support button is placeholder.  

For this issue, either figure out what the support button should do, or remove the placeholder.

**Comment by invincibleJai** [comment]
Closing this as been fixed with https://github.com/janus-idp/backstage-plugins/pull/1205
