### ISSUE TITLE
🔌 Plugin: OCI Registry (Nexus)

### ISSUE THREAD

**Issue by serenamarie125** [janus-idp/backstage-plugins#116]
## Goal
The goal of this epic is to develop a new Backstage plugin in the Janus repo. This plugin should provide Backstage user with the ability to view details of an image related to a catalog resource that was deployed by a **Nexus** image.

## Acceptance criteria
- [ ] Users should be able to view the tags, last update and SHA of an image related to a catalog deployed by a **Nexus** image 

## Requirements
- [ ] Plugin
- [ ] Test plan
- [ ] Installation documentation
- [ ] End user documentation

## Issues in Epic
- https://github.com/janus-idp/backstage-showcase/issues/381
- https://github.com/janus-idp/backstage-plugins/issues/567 [Eng]
- https://github.com/janus-idp/backstage-plugins/issues/568 [QE]
- https://github.com/janus-idp/backstage-plugins/issues/569 [Doc]

## Notes
There is a question as to if there should be an OCI Registry frontend plugin which has a number of backend plugins (Quay, ECR, GCR, Nexus, JFrog)

**Additional context**

**Comment by ekafeel** [comment]
@schultzp2020 Just wanted to check if this is in progress?

**Comment by schultzp2020** [comment]
@ekafeel Yes - [PR](https://github.com/janus-idp/backstage-plugins/issues/567)
