### ISSUE TITLE
[Orchestrator Backend] The `catalog:register` action attempts to create a location with a target of `null`.

### ISSUE THREAD

**Issue by Zaperex** [janus-idp/backstage-plugins#1167]
### Describe the bug

When trying to utilize the orchestrator plugin, and running one of the create backend app workflows in [the example workflow repository](https://github.com/tiagodolphine/backstage-orchestrator-workflows) such as the [`spring-boot-backend` workflow](https://github.com/tiagodolphine/backstage-orchestrator-workflows/blob/d7933f0b851c1392f1deaf3c16d55a571a2f70ec/workflows/spring-boot-backend.sw.yaml#L193-L204), the workflow will create the repository but will not be able to register the corresponding component. Instead it will output the following in the logs saying it's registering `null` into the catalog:
```bash
backend:start: 2024-02-02T18:33:29.380Z orchestrator info Registering null in the catalog 
backend:start: 2024-02-02T18:33:29.389Z rootHttpRouter info ::1 - - [02/Feb/2024:18:33:29 +0000] "POST /locations HTTP/1.1" 400 - "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" type=incomingRequest
backend:start: 2024-02-02T18:33:29.413Z backstage error Request failed with status 500 {"error":{"name":"InputError","message":"request/body/target must be string","stack":"InputError: request/body/target must be string\n    at <anonymous> (/home/frkong/coding/janus-idp/backstage-showcase/node_modules/@backstage/backend-openapi-utils/src/stub.ts:42:10)\n    at handleReturn (/home/frkong/coding/janus-idp/backstage-showcase/node_modules/express-promise-router/lib/express-promise-router.js:24:23)\n    at /home/frkong/coding/janus-idp/backstage-showcase/node_modules/express-promise-router/lib/express-promise-router.js:55:9\n    at Layer.handle_error (/home/frkong/coding/janus-idp/backstage-showcase/node_modules/express/lib/router/layer.js:71:5)\n    at trim_prefix (/home/frkong/coding/janus-idp/backstage-showcase/node_modules/express/lib/router/index.js:326:13)\n    at /home/frkong/coding/janus-idp/backstage-showcase/node_modules/express/lib/router/index.js:286:9\n    at Function.process_params (/home/frkong/coding/janus-idp/backstage-showcase/node_modules/express/lib/router/index.js:346:12)\n    at next (/home/frkong/coding/janus-idp/backstage-showcase/node_modules/express/lib/router/index.js:280:10)\n    at Layer.handle_error (/home/frkong/coding/janus-idp/backstage-showcase/node_modules/express/lib/router/layer.js:67:12)\n    at trim_prefix (/home/frkong/coding/janus-idp/backstage-showcase/node_modules/express/lib/router/index.js:326:13)\n    at /home/frkong/coding/janus-idp/backstage-showcase/node_modules/express/lib/router/index.js:286:9\n    at Function.process_params (/home/frkong/coding/janus-idp/backstage-showcase/node_modules/express/lib/router/index.js:346:12)\n    at next (/home/frkong/coding/janus-idp/backstage-showcase/node_modules/express/lib/router/index.js:280:10)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"},"request":{"method":"POST","url":"/locations"},"response":{"statusCode":400}} type=errorHandler stack=Error: {"error":{"name":"InputError","message":"request/body/target must be string","stack":"InputError: request/body/target must be string\n    at <anonymous> (/home/frkong/coding/janus-idp/backstage-showcase/node_modules/@backstage/backend-openapi-utils/src/stub.ts:42:10)\n    at handleReturn (/home/frkong/coding/janus-idp/backstage-showcase/node_modules/express-promise-router/lib/express-promise-router.js:24:23)\n    at /home/frkong/coding/janus-idp/backstage-showcase/node_modules/express-promise-router/lib/express-promise-router.js:55:9\n    at Layer.handle_error (/home/frkong/coding/janus-idp/backstage-showcase/node_modules/express/lib/router/layer.js:71:5)\n    at trim_prefix (/home/frkong/coding/janus-idp/backstage-showcase/node_modules/express/lib/router/index.js:326:13)\n    at /home/frkong/coding/janus-idp/backstage-showcase/node_modules/express/lib/router/index.js:286:9\n    at Function.process_params (/home/frkong/coding/janus-idp/backstage-showcase/node_modules/express/lib/router/index.js:346:12)\n    at next (/home/frkong/coding/janus-idp/backstage-showcase/node_modules/express/lib/router/index.js:280:10)\n    at Layer.handle_error (/home/frkong/coding/janus-idp/backstage-showcase/node_modules/express/lib/router/layer.js:67:12)\n    at trim_prefix (/home/frkong/coding/janus-idp/backstage-showcase/node_modules/express/lib/router/index.js:326:13)\n    at /home/frkong/coding/janus-idp/backstage-showcase/node_modules/express/lib/router/index.js:286:9\n    at Function.process_params (/home/frkong/coding/janus-idp/backstage-showcase/node_modules/express/lib/router/index.js:346:12)\n    at next (/home/frkong/coding/janus-idp/backstage-showcase/node_modules/express/lib/router/index.js:280:10)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"},"request":{"method":"POST","url":"/locations"},"response":{"statusCode":400}}
backend:start:     at CatalogClient.addLocation (/home/frkong/coding/janus-idp/backstage-showcase/node_modules/@backstage/catalog-client/src/CatalogClient.ts:325:13)
backend:start:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
backend:start:     at Object.handler (/home/frkong/coding/janus-idp/backstage-showcase/node_modules/@backstage/plugin-scaffolder-backend/src/scaffolder/actions/builtin/catalog/register.ts:130:9)
backend:start:     at ScaffolderService.executeAction (/home/frkong/coding/janus-idp/backstage-showcase/dynamic-plugins-root/orchestrator-backend/src/service/ScaffolderService.ts:99:11)
backend:start:     at <anonymous> (/home/frkong/coding/janus-idp/backstage-showcase/dynamic-plugins-root/orchestrator-backend/src/service/router.ts:516:31)
```

Debugging the backend shows that the `body` field of the request `req` seems to have an invalid schema (contains the `catalogInfoUrl` field) when the [schema for the action in the upstream](https://github.com/backstage/backstage/blob/36dbf7e6a161b8d7320e4ebc521cd00e58e1b79d/plugins/scaffolder-backend/src/scaffolder/actions/builtin/catalog/register.ts#L44-L103) has `catalogInfoUrl` be mutually exclusive with `repoContentsUrl` and `catalogInfoPath`:
![image](https://github.com/janus-idp/backstage-plugins/assets/50030060/2f36cb53-0a06-4281-897c-7e60cf21be4e)

When testing with the regular scaffolder, the `body` field does not contain the `catalogInfoUrl` field. Used the [sprint-boot-backend scaffolder action](https://github.com/janus-idp/software-templates/blob/4a2bebf36d3d1b717c767c45a9be260b6d15ac05/templates/github/spring-boot-backend/template.yaml#L207-L212).
![image](https://github.com/janus-idp/backstage-plugins/assets/50030060/e410fec0-68b4-49a8-b6c9-8048db579b6f)

This in turn breaks the logic for the `catalog:register` action in the `scaffolder-backend`, resulting in a `null` `catalogInfoUrl` field being passed as the `target` field for the `addLocations` function of the `catalog-client`.
![image](https://github.com/janus-idp/backstage-plugins/assets/50030060/2baddbda-b513-4578-b576-5d745ec6f5f2)
![image](https://github.com/janus-idp/backstage-plugins/assets/50030060/9aefe8f6-fe7b-41ff-ae86-064041246263)

### Expected Behavior
The catalog entity is registered into the catalog without any issues

### What are the steps to reproduce this bug?

1. Setup the orchestrator frontend and backend plugin into the backstage-showcase (I dynamically installed them)
2. Have a valid github app or github token with permissions to create repositories, edit workflows, and repository content
3. Start the [`spring-boot-backend` workflow](https://github.com/tiagodolphine/backstage-orchestrator-workflows/blob/d7933f0b851c1392f1deaf3c16d55a571a2f70ec/workflows/spring-boot-backend.sw.yaml)
4. Observe that no catalog entity was ingested into the catalog (since location wasn't added properly)
5. Observe the backend logs above

### Versions of software used and environment
- Running the https://github.com/janus-idp/backstage-showcase/pull/897 build of the showcase with the new backend system
- `@janus-idp/backstage-plugin-orchestrator@1.3.0`
- `@janus-idp/backstage-plugin-orchestrator-backend-dynamic@1.2.0`

**Comment by pkliczewski** [comment]
@caponetto fyi
