### ISSUE TITLE
Fail the build if the yarn.lock file is changed after running yarn install

### ISSUE THREAD

**Issue by gashcrumb** [janus-idp/backstage-plugins#1169]
### What do you want to improve?

Often when running yarn install after updating the `yarn.lock` file contains changes.

### What is the current behavior?

This is not ideal as it means there's inconsistencies between what folks are committing and what is being tested in github actions.

### What will the new behavior be?

The build action will fail if there's changes to the `yarn.lock` file after running `yarn install`

See [this comment](https://github.com/janus-idp/backstage-plugins/pull/1143#issuecomment-1916880791) for more information:

**Comment by nickboldt** [comment]
See https://issues.redhat.com//browse/RHIDP-1203 for updates.
