### ISSUE TITLE
RBAC Plugin - Conditional policies

### ISSUE THREAD

**Issue by matdtr** [janus-idp/backstage-plugins#1241]
Hi, 

I have a vanilla backstage instance and i'm integrating the RBAC plugin.  Three questions: 
- At the moment CONDITIONAL policies can be configured only via API? 
- The conditional policies are supported in policy file? 
- Are groups supported in 'superUsers' configuration? 

I'm using:
 "@janus-idp/backstage-plugin-rbac": "^1.14.4",

Looking forward your feedback. 

BR

**Comment by AndrienkoAleksandr** [comment]
Hello, @matdtr. We introduced file support for RBAC conditions with help of the file in the yaml format. See more:

https://github.com/janus-idp/backstage-plugins/blob/e6a1968fbab04326346569ad4cffdefd28c3c4e6/plugins/rbac-backend/README.md#configuring-conditional-policies-via-file

**Comment by PatAKnight** [comment]
@matdtr Just wanted to check in and see if it was alright to close this issue out or if you had any other questions?

**Comment by matdtr** [comment]
> @matdtr Just wanted to check in and see if it was alright to close this issue out or if you had any other questions?

Hi @PatAKnight, sorry for late response yes it’s fine to close will give it a look on the update and test on my instance.
