### ISSUE TITLE
[Tekton plugin]- ACS Image check output UI is crashing the with errors.

### ISSUE THREAD

**Issue by karthikjeeyar** [janus-idp/backstage-plugins#1355]
### Describe the bug

Roxctl image check sometimes does not contain the response in expected format and it is causing the UI to break. 

![Screenshot from 2024-03-20 13-49-28](https://github.com/janus-idp/backstage-plugins/assets/9964343/771400c3-9097-4925-b310-e84cd9311222)

ACS image check log output (does not contain expected response):

```
STEP-REPORT 

{ "summary": {
   "CRITICAL": 0,
     "HIGH": 0,
      "LOW": 0,
       "MEDIUM": 0,
       "TOTAL": 0  
       }
   }
   ```
   Note: This does not happen all the times, it happens on some edge cases.

### Expected Behavior

UI should gracefully handles this type of response mismatch errors and should hide only the tab which is causing the error.

**Comment by rtaniwa** [comment]
@nickboldt @kadel given there is a PR up, if we can we should look to include this in RHDH 1.1.1 as this is an issue RHTAP was hoping to get addressed in their GA. They will be picking up RHDH 1.1.1 when it gets released. I would assume that the RHTAP team will be able to verify the fix with their engineers or QE, so I don't expect any impact to the RHDH team other than maybe a release note entry and a small PR to pull in this version of the plugin.

**Comment by nickboldt** [comment]
if we're including this in 1.1.1, do we want to be formal with the paperwork and have a JIRA for it, so that the docs team can add it to the RNaKI list of fixed issues? @hmanwani-rh FYI

**Comment by karthikjeeyar** [comment]
@nickboldt There is a JIRA ticket for this in RHTAPBUGS - https://issues.redhat.com/browse/RHTAPBUGS-1175

**Comment by nickboldt** [comment]
Can we resolve this since 3.5.12 is now in main and 1.1.x branches ?
