### ISSUE TITLE
Integrate Tooling with the codebase for checking codequality

### ISSUE THREAD

**Issue by riginoommen** [janus-idp/backstage-plugins#136]
**Is your feature request related to a problem? Please describe.**
If a Pull Request is opened up. identifying some code vulnerabilities and security issues is hard with human efforts and it's a time taking process. To address this issue can we set up some automation to identify the quality of the code and the incoming pull-requests to the codebase

**Describe the solution you'd like**
Integrating tools like can help with the mentioned automation
- [x] Codecov

**Describe alternatives you've considered**
- [ ] Snyk
- [ ] codeclimate
- [ ] sonarcloud

**Additional context**
N/A

**Comment by tumido** [comment]
Thanks to @christophe-f we have sonarcloud enabled now. It's already used in the showcase repo, so it makes sense to use something the community is already used to and share the same setup here as well.

I'm gonna close this issue for now. Feel free to reopen if it's not sufficient. 🙂
