### ISSUE TITLE
New role and permissions are not working when we are creating from RBAC UI.🔌 Plugin: 

### ISSUE THREAD

**Issue by ravimandalasapient** [janus-idp/backstage-plugins#1542]
### 🔖 Summary

New role and permissions are not working when we are creating from RBAC UI.

### 👀 Have you spent some time to check if this plugin request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by ravimandalasapient** [comment]
@invincibleJai @PatAKnight

I am observing one issue with create a role, its permissions for the particular plugin and assigned to user with RBAC plugin UI which is using rest internally. When i try to login with that user,i will not be able to see that plugin. But
if upload these details using policy plugin then that user is able to see that plugin.
Is there any extra configurations are required to make rbac rest also works.

**Comment by crazy-canux** [comment]
the same issue.  I think it's caused by replicas. 
workaround: restart deployment.

related with https://github.com/janus-idp/backstage-plugins/issues/1492

**Comment by PatAKnight** [comment]
@ravimandalasapient Sorry it has been awhile. I wanted to check back and see if this is a problem that you are still running into?

**Comment by PatAKnight** [comment]
I am going to go ahead and move this to close. If you find this in error, don't hesitate to either reopen or open up a new issue. 
Thanks!
