### ISSUE TITLE
Update `package.json` of current plugins with additional metadata and set sane defaults for future plugisn

### ISSUE THREAD

**Issue by tumido** [janus-idp/backstage-plugins#155]
**Goal**
A new plugin is populated with a `package.json` that is missing some important metadata. Please make sure these values are populated for existing plugins and make sure the values are also pre-populated for new plugins.

Please read NPM documentation and suggest metadata that should be populated. Please invent a way how to populate these values for new plugins via native tools.

**What problem does this solve? Please describe.**
Less maintenance, more standardization etc.

**Acceptance criteria**
- [ ] All current plugins have `package.json` updated
- [ ] New future plugins will receive the same metadata

**Additional context**
Good first issue - learn about NPM, Yarn and backstage cli

**Comment by schwesig** [comment]
missing metadata we need:
- repository : github:janus-idp/backstage-plugins
- keywords : look up other npm backstage plugins and follow their keywords
- homepage : https://janus-idp.io/
- bugs :  https://github.com/janus-idp/backstage-plugins/issues

missing metadata we might need
- authors : see backstage authors
- contributors : see backstage contributors

missing metadata we need and already know how to automatically add it to new plugins
- private :  false --> setting flag with backstage-cli new script

**Comment by schwesig** [comment]
@tumido what about the second part: new future plugins will receive the same metadata?
open a new issue or reopen this again and try to find a solution?
