### ISSUE TITLE
🔌 Plugin: Argo - part 1

### ISSUE THREAD

**Issue by serenamarie125** [janus-idp/backstage-plugins#162]
## Goals
1. Evaluate existing community plugin to find issues and opportunities for improvement & enhancement
2. This epic aims to provide additional capabilities to the existing Roadie Argo plugin

### Identify issues that we want to address with existing upstream plugin
1. Issue with passing token
2. When there are issues with Argo, include error messages
3. Provide a link to the Argo UI
4. Update the ArgoCD history card to include the following 5 columns (see image below of deployment history view from OpenShift Console Environments page - we want the same display, but omit Environment): 
     1. Deployment status (need to confirm proper design pattern here, green/red dot maybe?)
     2. Deployment time
     3. Message
     4. Author
     5. Revision SHA 

## Issues in Epic
- [x] https://github.com/janus-idp/backstage-plugins/issues/84
- [x] https://github.com/janus-idp/backstage-plugins/issues/110

## Stakeholder sign-off
- [x] QE
- [ ] Doc

## Link to upstream
- https://github.com/RoadieHQ/roadie-backstage-plugins/issues/881

### Provides a deployment history view
I![Image](https://user-images.githubusercontent.com/12504403/217913712-f309422e-50ae-4119-a662-3e5a77891aed.png)

**Comment by yzhao583** [comment]
Issue: [https://github.com/RoadieHQ/roadie-backstage-plugins/issues/881](https://github.com/RoadieHQ/roadie-backstage-plugins/issues/881) has been done.
