### ISSUE TITLE
Feedback Plugin: 401 Unauthorized error

### ISSUE THREAD

**Issue by Longji-Kang** [janus-idp/backstage-plugins#1626]
### Describe the bug

We are implementing the feedback on our backstage instance, but we are getting a 401 Unauthorized when the front end plugin is making API calls to the backend. I think this is happening because the API calls from the front end are not using backstage's fetchApi and is not including any auth headers.

### Expected Behavior
The frontend should not have issues making API calls to the backend even if backend auth is enabled.

### What are the steps to reproduce this bug?

1. Enable backend auth on backstage
2. Setup feedback plugin's backend according to the docs
3. Setup feedback plugin's frontend according to the docs
4. Run backstage and try to provide feedback through the plugin

### Versions of software used and environment
@janus-idp/backstage-plugin-feedback version 1.2.5
@janus-idp/backstage-plugin-feedback version 1.1.6
Backstage version 1.26.5

**Comment by yashoswalyo** [comment]
I am working on fix, that will support backstage fetch API, which will automatically add auth headers to fetch calls

**Comment by Longji-Kang** [comment]
> I am working on fix, that will support backstage fetch API, which will automatically add auth headers to fetch calls

Thank you very much!
