### ISSUE TITLE
Bug: Topology not showing correct deployment and pod

### ISSUE THREAD

**Issue by PatAKnight** [janus-idp/backstage-plugins#163]
**Describe the bug**
The deployment and pod are not correctly showing in the topology plugin tab in the showcase app. 
**To Reproduce**

1. Go to 'topology tab in showcase app'

**Expected behavior**
Should show the correct information
**Screenshots**
![Screenshot from 2023-03-09 11-39-46](https://user-images.githubusercontent.com/82788581/224091612-d08be9c3-4666-4dba-b209-183c24813208.png)

![Screenshot from 2023-03-09 11-39-33](https://user-images.githubusercontent.com/82788581/224091658-3a735716-da47-4103-b319-ceda79cb5d26.png)

**Additional context**

**Comment by tumido** [comment]
cc @invincibleJai @divyanshiGupta

**Comment by invincibleJai** [comment]
paylod response for above https://gist.github.com/invincibleJai/09762d354807aa875da39f0da92af8c3
