### ISSUE TITLE
Certificate Error, Feedback plugin

### ISSUE THREAD

**Issue by boueida** [janus-idp/backstage-plugins#1678]
### Describe the bug

I have the feedback plugin running. I have set the email host, port, auth, and left secure false and left caCert Empty and commented out (tried both). Everytime I try to create a JIRA ticket, I get

cause: Error: unable to get local issuer certificate
[1]       at TLSSocket.onConnectSecure (node:_tls_wrap:1674:34)
[1]       at TLSSocket.emit (node:events:518:28)
[1]       at TLSSocket._finishInit (node:_tls_wrap:1085:8)
[1]       at ssl.onhandshakedone (node:_tls_wrap:871:12) {
[1]     code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY'
[1]   }
[1] }

A clear and concise description of what the bug is. (provide screenshots if applicable)

### Expected Behavior
The ticket is supposed to be created without any issues
![image](https://github.com/janus-idp/backstage-plugins/assets/116902290/3ba19b1e-8eef-450f-8e87-1816ff6b24d2)

**Comment by yashoswalyo** [comment]
Hey @boueida the `caCert` field should be under email
```yaml
feedback:
  integrations:
    email:
      host: "host_here"
      auth: { }
      caCert:

```
