### ISSUE TITLE
Feedback plugin

### ISSUE THREAD

**Issue by boueida** [janus-idp/backstage-plugins#1680]
### Describe the bug
When creating the annotations in catalog-info, we have to specify all the annotations or else the plugin won't work and will show that:
![image](https://github.com/janus-idp/backstage-plugins/assets/116902290/8492d518-85d9-4582-9642-78980d015e0f)

### Expected Behavior
The optional feedback/email-to has to be optional and not required.

### What are the steps to reproduce this bug?
Create a catalog-info as instructed and don't add feedback/email-to

**Comment by yashoswalyo** [comment]
Fixed in #1696
Now only `feedback/type` annotation is required in your catalog-info file

**Comment by yashoswalyo** [comment]
@boueida can you verify and close this issue?

**Comment by yashoswalyo** [comment]
@boueida can you verify and close this issue?

**Comment by yashoswalyo** [comment]
@boueida can you verify and close this issue?
