### ISSUE TITLE
Reminder: Upgrade to MUI v5 once supported upstream

### ISSUE THREAD

**Issue by tumido** [janus-idp/backstage-plugins#170]
MUI v5 is not yet supported upstream https://github.com/backstage/backstage/issues/7094

Reopen/update following PRs once resolved upstream:

- [ ] https://github.com/janus-idp/backstage-plugins/pull/169
- [ ] https://github.com/janus-idp/backstage-plugins/pull/168
- [ ] https://github.com/janus-idp/backstage-plugins/pull/742
- [ ] https://github.com/janus-idp/backstage-plugins/pull/743

**Comment by schultzp2020** [comment]
@invincibleJai we should look into this again. It's been a while since backstage has supported mui v5.

**Comment by invincibleJai** [comment]
> @invincibleJai we should look into this again. It's been a while since backstage has supported mui v5.

Yeah we should , have added a ticket in tech debt for it https://issues.redhat.com/browse/RHIDP-3829
