### ISSUE TITLE
Orchestrator Plugin - Not working with Backstage new backend auth service

### ISSUE THREAD

**Issue by BillKlineVT** [janus-idp/backstage-plugins#1700]
### Describe the bug

Backstage 1.24.0 changed the backend auth which protects all routes by default by requiring authentication, as described in the docs [here](https://backstage.io/docs/auth/service-to-service-auth/)

When following the documentation for adding the orchestrator plugin, there is no mention of setting up tokens for this backend auth.

The error seen when attempting to access the Orchestrator page in Backstage is shown below:
![image](https://github.com/janus-idp/backstage-plugins/assets/8855701/ae86ce5c-2968-477b-b75b-408335fcdd0f)

It appears that the orchestrator plugin is not configured to work with the new Backstage backend auth system.

### Expected Behavior
Starting Backstage with the orchestrator plugin enabled results in a functioning orchestrator page/service

### What are the steps to reproduce this bug?

1. Install orchestrator plugin to Backstage 1.27.2 following [the Readme section for the new backend](https://github.com/janus-idp/backstage-plugins/tree/main/plugins/orchestrator#setting-up-the-orchestrator-backend-package-for-the-new-backend)
2. Start Backstage
3. Go to the Orchestrator page

### Versions of software used and environment
Backstage 1.27.2
@janus-idp/backstage-plugin-orchestrator-backend 1.8.7
@janus-idp/backstage-plugin-orchestrator 1.12.6

**Comment by BillKlineVT** [comment]
Refer to a similar issue seen in the GitLab plugin before the new backend auth was supported: https://github.com/backstage/backstage/issues/23942

**Comment by BillKlineVT** [comment]
Waiting for the next release of the orchestrator (front end) plugin to see if what was added in #1599 fixed it

**Comment by BillKlineVT** [comment]
@batzionb any idea why the front end plugin wasn't updated when #1599 was merged?  Was it all part of the common package?

**Comment by batzionb** [comment]
Hi @BillKlineVT,

I tested it on backstage 1.27
There was some delay in the release of the packages, the versions with the fix were released yesterday.

The authentication works with the following versions:
@janus-idp/backstage-plugin-orchestrator": "1.13.0"
@janus-idp/backstage-plugin-orchestrator-backend": "1.9.1"

However, there is a separate issue with the workflow viewer, so when going into one of the workflows, you'll see an error screen. You can close and the following error screen and continue without the viewer. We'll keep track of this in a separate Jira issue.

**Comment by BillKlineVT** [comment]
@batzionb thank you for following up!

I just bumped everything to latest tonight and can confirm I am able to load the Workflow Orchestrator page on Backstage!

@janus-idp/backstage-plugin-orchestrator 1.13.2
@janus-idp/backstage-plugin-orchestrator-common 1.8.0
@janus-idp/backstage-plugin-orchestrator-backend 1.9.3

Good to close this if you concur

**Comment by batzionb** [comment]
Thanks for the update @BillKlineVT!
I'm closing the issue.
