### ISSUE TITLE
Custom action: Create a GH organization

### ISSUE THREAD

**Issue by serenamarie125** [janus-idp/backstage-plugins#172]
## Goal
This epic aims to enhance the experience for Platform Engineers creating GPTs.  We will provide 2 new custom actions which Platform Engineers to take advantage of:
1. Create a GH organization

## Acceptance criteria
- [ ] Users should be able to use a custom action to create a GH organization in their GPT.

## Requirements
- [ ] Custom action
- [ ] Test plan
- [ ] Installation documentation
- [ ] End user documentation

## Issues in Epic
- [x] #173 

**Additional context**
Here are some examples of scaffolder-actions in other repos: 
- https://github.com/backstage/backstage/blob/f00e03c38f0de6487af990e0410f4219eb1a8e28/plugins/scaffolder-backend/src/scaffolder/actions/builtin/createBuiltinActions.ts#L40
- https://github.com/RoadieHQ/roadie-backstage-plugins/tree/main/plugins/scaffolder-actions

**Comment by schultzp2020** [comment]
@jasperchui I am a little confused why creating a GH Org custom action is in the same epic as the ServiceNow custom action. I also thought that we concluded creating a GH Org is currently impossible through an API. 

cc @kadel
