### ISSUE TITLE
Custom action: Create a GH organization

### ISSUE THREAD

**Issue by serenamarie125** [janus-idp/backstage-plugins#173]
## Description
As a Platform Engineer, I want to be able to use a custom action to **create a GH organization** in my GPT.

**Comment by kadel** [comment]
I just found out that GitHub doesn't provide API for creating organizations on github.com (Free, Pro, & Team).
There is a way to create GH organization programmatically, but it is available only for **GitHub Enterprise Cloud** and **GitHub Enterprise Server** using GraphQL API ([`CreateEnterpriseOrganization`](https://docs.github.com/en/enterprise-cloud@latest/graphql/reference/mutations#createenterpriseorganization)).

We can create custom actions for this, but only those using GitHub Enterprise will be able to use this. Normal github.com users (even paying once) won't be able to use this.

**Comment by christophe-f** [comment]
That's correct this is for GitHub Entreprise only. Large entreprises won't host their code to public GitHub.

**Comment by kadel** [comment]
I have code for custom action that can successfully create an organization on GitHub Enterprise Server. 

But there is a problem that could be a blocker for this. 
It works only when Backstage GitHub integration is configured using a personal access token. It doestn't work when Backstaes is configured to use GitHub App.

So far, I could not figure out how to give GitHub App permissions so it can create orgs. Access token requires having `admin:enterprise` to be able to create orgs. The permission model for GitHub App is different, and there is no such permission. 
Based on all research I have done so far, this might not be even possible :-(
