### ISSUE TITLE
Custom action: Create a SonarQube project

### ISSUE THREAD

**Issue by serenamarie125** [janus-idp/backstage-plugins#177]
## Description
As a Platform Engineer, I want to be able to use a custom action to **create a SonarQube project** in my GPT.

**Comment by jlmayorga** [comment]
@serenamarie125: Would it make sense to create an action for SonarQube [Applications](https://docs.sonarqube.org/latest/user-guide/applications/) as well?

**Comment by christophe-f** [comment]
That would be a nice addition. Maybe for a v2?

Currently, I'm not sure if the SonarQube plugin handles that (Applications):
- https://github.com/backstage/backstage/blob/master/plugins/sonarqube/README.md
- https://github.com/backstage/backstage/blob/master/plugins/sonarqube-backend/README.md

**Comment by regicsolutions** [comment]
Agree that supporting both Projects and Applications would be great

**Comment by rtaniwa** [comment]
Delivered via https://github.com/janus-idp/backstage-plugins/pull/206
