### ISSUE TITLE
🔌 Plugin: Parodos

### ISSUE THREAD

**Issue by serenamarie125** [janus-idp/backstage-plugins#178]
## Goal
This epic aims to develop a new Backstage plugin in the Janus repo. This plugin should allow Backstage users to access guided flows driven by the Parodos workflow engine.

## Acceptance criteria
- [ ] Users should be able to xxx (need to flesh out the first version of ACs)
- [ ] 
## Requirements
- [ ] Plugin
- [ ] Test plan
- [ ] Installation documentation
- [ ] End user documentation

## Issues in Epic
- [ ] tbd

## Notes
Parodos workflow engine - community repo: https://github.com/redhat-developer/parodos

**Comment by pkliczewski** [comment]
We track this work on our end here: https://issues.redhat.com/browse/FLPATH-203

**Comment by regicsolutions** [comment]
Are there any docs on how to implement the parodos workflow engine?

**Comment by pkliczewski** [comment]
> Are there any docs on how to implement the parodos workflow engine?

Do you mean how to implement workflows? if so you can find some info and examples [here](https://github.com/parodos-dev/parodos/tree/main/workflow-examples)

**Comment by regicsolutions** [comment]
> > Are there any docs on how to implement the parodos workflow engine?
> 
> 
> 
> Do you mean how to implement workflows? if so you can find some info and examples [here](https://github.com/parodos-dev/parodos/tree/main/workflow-examples)

This helps, regarding the example is there a dependency on [tibco](https://www.tibco.com/products/business-process-management)? 

Is there a list of supported workflow engines?

**Comment by pkliczewski** [comment]
We have a task which can post to tibco. That is why we have a dependency on tibco client.

At the moment we support one workflow engine (easy-flows) but we have an epic to write an abstraction and support more engines.

**Comment by regicsolutions** [comment]
> We have a task which can post to tibco. That is why we have a dependency on tibco client.
> 
> 
> 
> At the moment we support one workflow engine (easy-flows) but we have an epic to write an abstraction and support more engines.

Thanks for sharing, is there currently a list of engines in scope?

**Comment by pkliczewski** [comment]
> 
> Thanks for sharing, is there currently a list of engines in scope?

No list at this time
