### ISSUE TITLE
SonarQube plugin fail yarn tsc

### ISSUE THREAD

**Issue by jaalvarezuria** [janus-idp/backstage-plugins#1799]
### Describe the bug
After following installation steps https://github.com/janus-idp/backstage-plugins/blob/08525c9fa87e2d3a9ca64ddf4876e543311d6b0d/plugins/sonarqube-actions/README.md and installing the action on the new backend, I´ve made a yarn tsc and I have the error:

![image](https://github.com/janus-idp/backstage-plugins/assets/84963697/521985ca-fd77-437d-9f90-d9bc8fd87a07)

### Expected Behavior

Plugin should install with no errors

### What are the steps to reproduce this bug?

1. …
2. …
3. …

**Comment by PatAKnight** [comment]
Hmm, I did not run into the error that you are seeing. I tested it with both Backstage `1.29.2` and `1.30.0` with SonarQube actions `1.7.1`. Do you mind sharing what versions of Backstage and SonarQube actions that you are using?

**Comment by PatAKnight** [comment]
@jaalvarezuria I believe that this issue may have already been fixed and will go ahead and close this issue. If you find this in error please feel free to reopen this.
