### ISSUE TITLE
Unclear when Orchestrator Plugin should use single-container Sonata Flow vs. entire Sonata Flow K8s Operator / Knative / OpenShift ecosystem

### ISSUE THREAD

**Issue by BillKlineVT** [janus-idp/backstage-plugins#1815]
### What do you want to improve?
Need clarification on when to use "dev mode" deployment of a single-container SonataFlow vs. the Orchestrator Helm chart/operator to support the Orchestrator plugin.  Are there certain features/use cases that are only supported by the more heavyweight operator?

### What does the current documentation state?
The Orchestrator plugin is configured by default ("[dev mode](https://github.com/janus-idp/backstage-plugins/blob/7403c42652ad9fdd67f07a599f29a8105e2b4cd4/plugins/orchestrator-backend/src/service/DevModeService.ts#L132)") to create a single docker container as the `backstage-internal-sonataflow` service to support Backstage calls for Orchestrator workflows.

When considering a production use of the Orchestrator plugin, the documentation steers one to much more complex deployment of OpenShift, and the [Orchestrator Helm chart](https://www.parodos.dev/orchestrator-helm-chart/) which deploys RHDH (Red Hat Developer Hub) Backstage, OpenShift Serverless Logic Operator (with Data-Index and Job Service), OpenShift Serverless Operator (Knative Eventing and Knative Serving).

### What would you like to be added/updated in the documentation?
Examples of when a single-container SonataFlow should be used vs. when the full SonataFlow Orchestrator operator should be used

**Comment by batzionb** [comment]
@masayag

**Comment by masayag** [comment]
@BillKlineVT Could you please review the content at [this blog post](https://www.parodos.dev/blog/devmode-vs-prodmode/) to see if it contains the information you need?

**Comment by BillKlineVT** [comment]
The blog post looks great!  Thank you for taking the time to lay out the differences!
