### ISSUE TITLE
[RBAC] Role precedence when user is part of 2 groups

### ISSUE THREAD

**Issue by SmajlovicA** [janus-idp/backstage-plugins#1828]
### Describe the bug

I have user which is part of 2 groups for example:
- group:default/team_a
- group:default/team_b

In role team_a user has **deny** access to create entity in catalog, and in role team_b have access to **allow**. 
Which role will take precedence? Here I only added an example, but in my backstage deployment I have the latest version of the RBAC plugin and Backstage (1.28.0). I have a user that is part of 2 groups (groups and users are discovered via GitHub org) and for some reason user in this example has deny access instead of allow (both groups are children).

```csv
p, role:default/team_a, catalog.entity.create, create, deny
p, role:default/team_b, catalog.entity.create, create, allow

g, group:default/team_a, role:default/team_a
g, group:default/team_b, role:default/team_b
```

A clear and concise description of what the bug is. (provide screenshots if applicable)

### Expected Behavior

I am expecting that if user is part of two groups which has same resource but different authorization that allow will take precedence.

### What are the steps to reproduce this bug?

1. Add user in 2 groups and create RBAC (csv) with 2 groups and 2 roles.
2. For some reason user match role that has deny instead of allow rule.

```csv
p, role:default/team_a, catalog.entity.create, create, deny
p, role:default/team_b, catalog.entity.create, create, allow

g, group:default/team_a, role:default/team_a
g, group:default/team_b, role:default/team_b
```

### Versions of software used and environment
OS:   Darwin 23.5.0 - darwin/arm64
node: v18.20.3
yarn: 1.22.22
cli:  0.26.7 (installed)
backstage:  1.28.0

Dependencies:
  @backstage/app-defaults                                          1.5.6
  @backstage/backend-app-api                                       0.5.14, 0.7.6
  @backstage/backend-common                                        0.19.10, 0.21.7, 0.22.0, 0.23.0
  @backstage/backend-defaults                                      0.3.0
  @backstage/backend-dev-utils                                     0.1.4
  @backstage/backend-openapi-utils                                 0.1.12
  @backstage/backend-plugin-api                                    0.6.19
  @backstage/backend-tasks                                         0.5.24
  @backstage/backend-test-utils                                    0.3.8
  @backstage/catalog-client                                        1.6.5
  @backstage/catalog-model                                         1.5.0
  @backstage/cli-common                                            0.1.14
  @backstage/cli-node                                              0.2.6
  @backstage/cli                                                   0.26.7
  @backstage/config-loader                                         1.8.1
  @backstage/config                                                1.2.0
  @backstage/core-app-api                                          1.12.6
  @backstage/core-compat-api                                       0.2.6
  @backstage/core-components                                       0.12.5, 0.13.10, 0.14.8
  @backstage/core-plugin-api                                       1.9.3
  @backstage/dev-utils                                             1.0.33
  @backstage/e2e-test-utils                                        0.1.1
  @backstage/errors                                                1.2.4
  @backstage/eslint-plugin                                         0.1.8
  @backstage/frontend-plugin-api                                   0.6.6
  @backstage/integration-aws-node                                  0.1.12
  @backstage/integration-react                                     1.1.28
  @backstage/integration                                           1.12.0
  @backstage/plugin-api-docs                                       0.11.6
  @backstage/plugin-app-backend                                    0.3.68
  @backstage/plugin-app-node                                       0.1.19
  @backstage/plugin-auth-backend-module-atlassian-provider         0.2.0
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.1.11
  @backstage/plugin-auth-backend-module-azure-easyauth-provider    0.1.2
  @backstage/plugin-auth-backend-module-bitbucket-provider         0.1.2
  @backstage/plugin-auth-backend-module-cloudflare-access-provider 0.1.2
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.14
  @backstage/plugin-auth-backend-module-github-provider            0.1.16
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.16
  @backstage/plugin-auth-backend-module-google-provider            0.1.16
  @backstage/plugin-auth-backend-module-guest-provider             0.1.5
  @backstage/plugin-auth-backend-module-microsoft-provider         0.1.14
  @backstage/plugin-auth-backend-module-oauth2-provider            0.2.0
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.12
  @backstage/plugin-auth-backend-module-oidc-provider              0.2.0
  @backstage/plugin-auth-backend-module-okta-provider              0.0.12
  @backstage/plugin-auth-backend-module-onelogin-provider          0.1.0
  @backstage/plugin-auth-backend                                   0.22.6
  @backstage/plugin-auth-node                                      0.4.14
  @backstage/plugin-auth-react                                     0.1.3
  @backstage/plugin-catalog-backend-module-github-org              0.1.14
  @backstage/plugin-catalog-backend-module-github                  0.6.2
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.17
  @backstage/plugin-catalog-backend-module-unprocessed             0.4.6
  @backstage/plugin-catalog-backend                                1.23.0
  @backstage/plugin-catalog-common                                 1.0.24
  @backstage/plugin-catalog-graph                                  0.4.6
  @backstage/plugin-catalog-import                                 0.12.0
  @backstage/plugin-catalog-node                                   1.12.1
  @backstage/plugin-catalog-react                                  1.12.1
  @backstage/plugin-catalog-unprocessed-entities-common            0.0.2
  @backstage/plugin-catalog-unprocessed-entities                   0.2.5
  @backstage/plugin-catalog                                        1.21.0
  @backstage/plugin-devtools-backend                               0.3.5
  @backstage/plugin-devtools-common                                0.1.10
  @backstage/plugin-devtools                                       0.1.15
  @backstage/plugin-events-node                                    0.3.5
  @backstage/plugin-home-react                                     0.1.14
  @backstage/plugin-home                                           0.7.5
  @backstage/plugin-kubernetes-backend                             0.18.0
  @backstage/plugin-kubernetes-common                              0.8.0
  @backstage/plugin-kubernetes-node                                0.1.13
  @backstage/plugin-kubernetes-react                               0.4.0
  @backstage/plugin-kubernetes                                     0.11.11
  @backstage/plugin-notifications-common                           0.0.4
  @backstage/plugin-notifications-node                             0.2.0
  @backstage/plugin-org                                            0.6.26
  @backstage/plugin-permission-backend-module-allow-all-policy     0.1.16
  @backstage/plugin-permission-backend                             0.5.43
  @backstage/plugin-permission-common                              0.7.14
  @backstage/plugin-permission-node                                0.7.30
  @backstage/plugin-permission-react                               0.4.23
  @backstage/plugin-proxy-backend                                  0.5.0
  @backstage/plugin-scaffolder-backend-module-azure                0.1.11
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.1.9
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.1.9
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.2.9
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.11
  @backstage/plugin-scaffolder-backend-module-gitea                0.1.9
  @backstage/plugin-scaffolder-backend-module-github               0.3.0
  @backstage/plugin-scaffolder-backend-module-gitlab               0.4.1
  @backstage/plugin-scaffolder-backend                             1.22.9
  @backstage/plugin-scaffolder-common                              1.5.3
  @backstage/plugin-scaffolder-node                                0.4.5
  @backstage/plugin-scaffolder-react                               1.9.0
  @backstage/plugin-scaffolder                                     1.21.0
  @backstage/plugin-search-backend-module-catalog                  0.1.25
  @backstage/plugin-search-backend-module-explore                  0.1.25
  @backstage/plugin-search-backend-module-pg                       0.5.28
  @backstage/plugin-search-backend-module-techdocs                 0.1.24
  @backstage/plugin-search-backend-node                            1.2.24
  @backstage/plugin-search-backend                                 1.5.10
  @backstage/plugin-search-common                                  1.2.12
  @backstage/plugin-search-react                                   1.7.12
  @backstage/plugin-search                                         1.4.12
  @backstage/plugin-signals-node                                   0.1.5
  @backstage/plugin-signals-react                                  0.0.4
  @backstage/plugin-techdocs-backend                               1.10.6
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.11
  @backstage/plugin-techdocs-node                                  1.12.5
  @backstage/plugin-techdocs-react                                 1.2.5
  @backstage/plugin-techdocs                                       1.10.6
  @backstage/plugin-user-settings-common                           0.0.1
  @backstage/plugin-user-settings                                  0.8.7
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.5.6
  @backstage/theme                                                 0.2.19, 0.4.4, 0.5.6
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.8

**Comment by PatAKnight** [comment]
Thank you for this bug report.

We actually have a deny by default approach with a precedence for deny. So, if there are no permission policies or if there are matching permission policies where one of them has a deny effect, we will override with a deny. You can see this set up in our [policy model](https://github.com/janus-idp/backstage-plugins/blob/main/plugins/rbac-backend/src/service/permission-model.ts#L9) which matches with the deny override rule as seen in this [section](https://casbin.org/docs/syntax-for-models/#policy-effect) of the Casbin docs.

**Comment by SmajlovicA** [comment]
Thank you so much for the replay. I checked casbin rules and I assumed that is configured:

That's okay, I thought that I made a mistake somewhere.

We can close this issue.

Kind regards
