### ISSUE TITLE
3scale backend plugin - Only first spec gets imported

### ISSUE THREAD

**Issue by maarten-vandeperre** [janus-idp/backstage-plugins#1836]
### Describe the bug

When you create a product in 3scale (ProductA) and you add a first spec (i.e., products > ProductA > ActiveDocs > create new spec) SpecA and you add a second spec (SpecB), both with an Open API endpoint definition, then, when imported by backstage, only the APIs mentioned in the first spec are available.

### Expected Behavior

I would expect that both specs are available either via a concatenation in the backstage API list as '<productName>_<specName>' or otherwise as productName (i.e., as is) in the listing, but that you have both the specs available in the "definition" section

### What are the steps to reproduce this bug?

see bug description

### Versions of software used and environment

RH Developer Hub Version: 1.1.2
Backstage Version: 1.23.4
On OpenShift

**Comment by AndrienkoAleksandr** [comment]
We merged fix: https://github.com/backstage/community-plugins/pull/1249
