### ISSUE TITLE
CLI export-dynamic-plugin fails after backstage update

### ISSUE THREAD

**Issue by johanneswuerbach** [janus-idp/backstage-plugins#1843]
### Describe the bug

Trying the export a package with `@janus-idp/cli@1.11.1 package export-dynamic-plugin --clean` fails with an error after updating backstage using `yarn backstage-cli versions:bump --release 1.27.7`:

```
Error: Backend plugin is not valid for dynamic loading: it should either export a BackendFeature or BackendFeatureFactory as default export, or export a const dynamicPluginInstaller: BackendDynamicPluginInstaller field as dynamic loading entrypoint
```

### Expected Behavior

`@janus-idp/cli@1.11.1 package export-dynamic-plugin --clean` should work as before.

### Debugging

There has been an upstream change https://github.com/backstage/backstage/pull/25098, which is potentially affecting the validate export detection logic of the CLI https://github.com/janus-idp/backstage-plugins/blob/582cf36da48f21f7aa31075430bf566a818a3cfa/packages/cli/src/commands/export-dynamic-plugin/backend-utils.ts#L101-L123.

Sadly this upstream change has been released as a patch release, so everyone locking to `^0.6.x` will soon get this change.

Locking the version `"@backstage/backend-plugin-api": "0.6.18"` inside the `package.json` of the respective plugin fixes the build.

**Comment by gashcrumb** [comment]
FYI this has been fixed by https://github.com/janus-idp/backstage-plugins/pull/2059, thanks @JessicaJHee
