### ISSUE TITLE
🔌 Plugin: Rebranding should move into a standalone plugin

### ISSUE THREAD

**Issue by serenamarie125** [janus-idp/backstage-plugins#208]
## Goal
This epic aims to provide a mechanism to rebrand the Backstage portal without having to rebuild or redeploy the Backstage application.

## Acceptance Criteria

- [ ] As a platform engineer, I want to be able to update the logo without having to rebuild or redeploy.
- [ ] As a platform engineer, I want to be able to change the primary color of the Backstage portal without having to rebuild or redeploy.

## Issues in Epic
- [x] #233 
- [x] #234

**Comment by serenamarie125** [comment]
@christophe-f could you add appropriate stories?

**Comment by rtaniwa** [comment]
Renamed the abstract as while we delivered the function of rebranding dev preview, we would ideally have this broken into a separate plugin. So this issue is really to track that change as part of our technical debt.

**Comment by kadel** [comment]
As discussed in the triage call, we are not doing this for Milestone 3, and not for Milestone 4.
Users will be able to customize branding using https://github.com/janus-idp/backstage-showcase/issues/540
