### ISSUE TITLE
[rbac-backend] Error: Plugin 'permission' is already registered

### ISSUE THREAD

**Issue by gluckzhang** [janus-idp/backstage-plugins#2082]
### Describe the bug

As mentioned in the documentation [here](https://github.com/janus-idp/backstage-plugins/blob/main/plugins/rbac-backend/README.md#setup-permision-framework), we need to set up the Backstage permission framework first.

For the new Backend system, I added the following code to `packages/backend/src/index.ts`:

```ts
backend.add(import('@backstage/plugin-permission-backend/alpha'));
backend.add(import('@janus-idp/backstage-plugin-rbac-backend'));
```

When run `yarn dev` from the root folder, I get the following error:

```
[1]             throw new Error(`Plugin '${r.pluginId}' is already registered`);
[1]                   ^
[1] Error: Plugin 'permission' is already registered
```

I find that both `@backstage/plugin-permission-backend/alpha` and `@janus-idp/backstage-plugin-rbac-backend` use the same plugin id (`permission`), but I am not sure about how to fix it.

### Expected Behavior

Backstage is up and running.

### What are the steps to reproduce this bug?

1. Follow the example [here](https://github.com/backstage/backstage/blob/master/packages/backend/src/index.ts) to setup Backstage permission framework
2. Add @janus-idp/backstage-plugin-rbac-backend
3. run yarn dev from the root folder

### Versions of software used and environment
- Backstage 1.27.0
- @backstage/plugin-permission-backend 0.5.42
- @janus-idp/backstage-plugin-rbac-backend@npm 4.10.0

**Comment by gluckzhang** [comment]
Hi again, after a bit more exploration, I think only adding `backend.add(import('@janus-idp/backstage-plugin-rbac-backend'));` is sufficient because the documentation also mentions that "this plugin provides a dynamic policy that replaces the traditional one, there's no need to create a policy manually."

In the beginning, the only misleading part to me is that we need to set up the Backstage permission framework first, while Backstage documentation says I need to add `backend.add(import('@backstage/plugin-permission-backend/alpha'));` in order to enable the permission framework.

Please correct me if the interpretation above is wrong. Furthermore, great job on this RBAC plugin. I see that it also uses Casbin as the rule engine, which is very cool. Thanks!

**Comment by PatAKnight** [comment]
Sorry for just now getting back to you on this. You are correct that it is misleading and that you only need `backend.add(import('@janus-idp/backstage-plugin-rbac-backend'));`, the docs haven't been updated completely to reflect the new changes that have been made to Backstage. I'll make some time to review the `Setup Permission Framework` section to see if it is still relevant. Thanks for this!

**Comment by gluckzhang** [comment]
Sounds great. Thanks @PatAKnight !
