### ISSUE TITLE
[tekton] incorrect image path in dist

### ISSUE THREAD

**Issue by JounQin** [janus-idp/backstage-plugins#2099]
### Describe the bug

```log
ERROR in ../../node_modules/@janus-idp/backstage-plugin-tekton/dist/utils/image-utils.esm.js 1:0-70
Module not found: Error: Can't resolve '../plugins/tekton/src/imgs/signed-badge.svg' in '/Users/JounQin/Workspaces/Alauda/octopus/node_modules/@janus-idp/backstage-plugin-tekton/dist/utils'
```

Similar issue #1527

### What are the steps to reproduce this bug?

https://unpkg.com/browse/@janus-idp/backstage-plugin-tekton@3.12.3/dist/utils/image-utils.esm.js

### Versions of software used and environment

`@janus-idp/backstage-plugin-tekton@3.12.3`

**Comment by nicolasfagotti** [comment]
Same issue here :)

**Comment by karthikjeeyar** [comment]
@JounQin @nicolasfagotti This fix landed in   [@janus-idp/backstage-plugin-tekton:3.12.7](https://www.npmjs.com/package/@janus-idp/backstage-plugin-tekton/v/3.12.7). Could you please try again with 3.12.7 ?

**Comment by nicolasfagotti** [comment]
It seems it is working now @karthikjeeyar. Thanks a lot!

**Comment by karthikjeeyar** [comment]
Thanks for confirmation, I am closing this issue.
