### ISSUE TITLE
🔌 Plugin: ACR (Azure Container Registry)

### ISSUE THREAD

**Issue by christophe-f** [janus-idp/backstage-plugins#216]
### 🔖 Summary

We want to have a plugin similar to Quay and JFrog Actifactory for ACR (Azure Container Registry).
ie: https://showcase.janus-idp.io/catalog/default/component/backstage-showcase/quay

### ✌️ Context

This new plugin could start from the JFrog Artifactory plugin [source code](https://github.com/janus-idp/backstage-plugins/tree/main/plugins/artifactory) as it will display similar information.

To get the data, we need to authenticate and use the Azure APIs. Here is the link to the [AzureCR REST API docs](https://learn.microsoft.com/en-us/rest/api/containerregistry/registries).

### 👀 Have you spent some time to check if this plugin request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by serenamarie125** [comment]
This is a dup of #166

**Comment by christophe-f** [comment]
This story is an issue. #166 is an epic

**Comment by yzhao583** [comment]
@christophe-f @serenamarie125 PR submitted. [https://github.com/janus-idp/backstage-plugins/pull/313](https://github.com/janus-idp/backstage-plugins/pull/313)

**Comment by serenamarie125** [comment]
Assigning to @invincibleJai to get this PR through the rework state
