### ISSUE TITLE
Display the Security scanner result in the Quay plugin 

### ISSUE THREAD

**Issue by christophe-f** [janus-idp/backstage-plugins#231]
**Describe the solution you'd like**
Quay does provide a security scan of the image. It would be great to see the number of vulnerabilities (and the severity) in the history table. If an image has an issue, a link should redirect to the Quay page with all the information.

https://developers.redhat.com/blog/2019/06/26/using-quay-io-to-find-vulnerabilities-in-your-container-images

**Comment by tumido** [comment]
@christophe-f @RobotSail is already working on something to support this. However, we thought it may be useful to display the vulnerabilities directly in Backstage rather than forwarding user to Quay UI. We though of implementing a subroute like Github Actions plugin does for workflow runs. WDYT? Would that be desirable?

**Comment by christophe-f** [comment]
I remember seeing some work on this but not a GitHub issue to track it. If it's a duplicate issue, feel free to close this one.

Showing the all the information in the plugin would be awesome. If it's too much work, we could do in phases. First show the number and severity. In a future release, display all the information.

**Comment by RobotSail** [comment]
@christophe-f I don't think it will be too much work. In terms of the more complex components, would we be able to split those off from the main Quay UI so we can reuse them in this plugin?

**Comment by RobotSail** [comment]
Additionally, would we want the tag security details page be keyed by the tag name or tag digest?

**Comment by tumido** [comment]
Let's do a tag digest. It's unique, with less room for error and confusion between images/repos. 🙂
