### ISSUE TITLE
Display the Jfrog Xray info the the Jfrog Artifactory

### ISSUE THREAD

**Issue by christophe-f** [janus-idp/backstage-plugins#232]
**Describe the solution you'd like**
Jfrog does provide a security scan with Xray. It would be great to see the number of vulnerabilities (and the severity) in the Jfrog Artifactory history table. If an image has an issue, a link should redirect to the Jfrog Artifactory page with all the information.

**Comment by regicsolutions** [comment]
Being able to visualize a sbom report would be nice - https://jfrog.com/help/r/jfrog-security-documentation/xray-sbom-report

**Comment by timdittler** [comment]
Addressed by https://github.com/janus-idp/backstage-plugins/pull/431
