### ISSUE TITLE
Topology plugin applicability to non-Openshift clusters?

### ISSUE THREAD

**Issue by Analect** [janus-idp/backstage-plugins#249]
Hi. I was wondering if your topology plugin is intended to work on non-OpenShift clusters?  Review [this](https://docs.openshift.com/container-platform/4.12/applications/odc-viewing-application-composition-using-topology-view.html), then perhaps no.

If yes, it can work on any cluster, I'm presuming that a resource on such a cluster should still be annotated with `app.openshift.io/connects-to` for the visualisation to work appropriately?  Would it make more sense to implement something like `backstage.io/connects-to` for this to remain somewhat generic functionality? Thanks.

```
app.openshift.io/connects-to': '[{"apiVersion": <RESOURCE_APIVERSION>,"kind": <RESOURCE_KIND>,"name": <RESOURCE_NAME>}]
```

**Comment by christophe-f** [comment]
Hi, the topology plugin should work with any Kubernetes versions. 

Feel free to join our Janus Community Slack channel for more discussion https://janus-idp.slack.com/join/shared_invite/zt-1pxtehxom-fCFtF9rRe3vFqUiFFeAkmg

**Comment by Analect** [comment]
Thanks for the assistance on [slack](https://janus-idp.slack.com/archives/C04EDTPJRK5/p1681324337243529).
