### ISSUE TITLE
🔌 Plugin: Quarkus

### ISSUE THREAD

**Issue by gastaldi** [janus-idp/backstage-plugins#254]
### 🔖 Summary

Support deploying applications using Quarkus as the backend	

### 🌐 Project website (if applicable)

https://quarkus.io

### 👀 Have you spent some time to check if this plugin request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by serenamarie125** [comment]
Thanks for sharing your idea!  Could you add more information
- what's the value add of the plugin
- what are the use cases which will be supported by this plugin?

**Comment by gastaldi** [comment]
> * what's the value add of the plugin

- The plugin will allow users to generate and deploy Quarkus applications 
- Facilitate adoption of the Red Hat Build of Quarkus (productized version)

> * what are the use cases which will be supported by this plugin?

- Developers will be able to start developing applications easily with Quarkus

**Comment by christophe-f** [comment]
Will it be offering more features than the current Golden Path template that we have in Janus?
https://github.com/janus-idp/software-templates/tree/main/scaffolder-templates/quarkus-backend-template

This template will create a repo, inject the Quarkus skeleton project, a CI pipeline and the ArgoCD manifests.

The Quarkus code is coming from the devfiles project.

**Comment by gastaldi** [comment]
I guess the main issue with the existing solution is that the content in https://github.com/janus-idp/software-templates/tree/main/scaffolder-templates/quarkus-backend-template/skeleton is static and potentially becoming stale between releases. 

This is akin to what I experienced while developing the [Red Hat Developers Launcher](https://developers.redhat.com/launch/) - keeping the sources in sync between releases becomes a maintenance nightmare.

I propose this plugin to invoke the Quarkus tooling APIs using code.quarkus.io (to generate the application) and registry.quarkus.io (to fetch the recommended releases for a particular platform) - and their productized counterparts - to generate the application instead. 

What comes next (setting up the CI pipeline and CD manifests) looks fine to me.

**Comment by christophe-f** [comment]
To keep things consistent with Backstage and the other templates, this could be a custom action instead of a plugin. The custom action could call the code.quarkus.io and generate the skeleton.

Currently the templates are basic, but the idea is that a customer can use that as a base and then tweak for their environments. Ie add custom security, actuator properties, etc so the devs don't have to care about this. It's automatically part of the template. 
Also accessing external apis could be a challenge in some setup.

**Comment by cmoulliard** [comment]
What should we do to integrate this work part of janus-idp ? @christophe-f

**Comment by gastaldi** [comment]
@cmoulliard would it be possible to integrate the code.quarkus.io frontend in the `create` link instead of introducing a new UI? Maybe with @ia3andy's help?

**Comment by cmoulliard** [comment]
> in the `create` link instead

Is it an action, another plugin, etc ? @gastaldi

**Comment by gastaldi** [comment]
I am looking at the screenshots in https://github.com/q-shift/backstage-plugins/tree/main and there is a `Create...` link there. I don't have enough knowledge in Backstage, but I'll guess it's a plugin?

**Comment by gastaldi** [comment]
Also, looking at the screenshots this looks really cool, great job!

**Comment by maxandersen** [comment]
> @cmoulliard would it be possible to integrate the code.quarkus.io frontend in the `create` link instead of introducing a new UI? Maybe with @ia3andy's help?

adding code.quarkus.io to backstage would not be a good fit for backstage. hence the plugin/templating approach.

**Comment by cmoulliard** [comment]
> I am looking at the screenshots in https://github.com/q-shift/backstage-plugins/tree/main and there is a `Create...` link there. I don't have enough knowledge in Backstage, but I'll guess it's a plugin?

As I mentioned :up:, our project includes UI fields to be used in a [backstage template](https://backstage.io/docs/features/software-templates/) and actions (= backend part ) to either call `code.quarkus.io` and get a zip of the project generated OR clone a quickstart github repository

@gastaldi

**Comment by maxandersen** [comment]
> @maxandersen I mean the UI only, not the code.quarkus.io external website BTW

Yes I get that. Code.quarkus ui is not what make sense to put into backstage. It's not how backstage flows/functions. It would be "alien". 

Hence why we made the plug-in that consist of part ui/part template config so you as platform end. can preconfigured at the level that makes snese for your org and integrate with rest of backstage/janus work.
