### ISSUE TITLE
Spike: Explore how to fetch and view pod logs of k8s backed resources

### ISSUE THREAD

**Issue by debsmita1** [janus-idp/backstage-plugins#271]
**Goal**
Explore how to fetch pod log information of k8s-backed resources

**What problem does this solve? Please describe.**
On OpenShift, users have the ability to view logs which helps them troubleshoot and understand what is happening to various resources created on the cluster. We want to bring the same experience to the Backstage app.

**Use cases**
As a developer, I should be able to fetch pod logs of the resources and view them in the Backstage app

**Acceptance criteria**
- [x] Explore and find out a way to fetch pod logs
- [ ] Create a story to utilize the information and view it in the app

**Comment by fmenesesg** [comment]
I think there are some work done on the backtage community for this topic https://github.com/backstage/backstage/pull/17120
We will have to wait until the PR gets merged

**Comment by tumido** [comment]
@debsmita1 is this related to the topology plugin and would you like to see it implemented in there? Or do you mean this as "how to do this in general"?

**Comment by debsmita1** [comment]
@tumido  We would need this for the topology plugin (to view pod logs of the workloads on topology) and also for the tekton plugin (to view the taskrun logs which are also pod logs)

**Comment by invincibleJai** [comment]
Have verified this and seems to work with the below dependency 

K8s backend:
"@backstage/plugin-kubernetes-backend": "^0.11.0"

K8s frontend:
"@backstage/plugin-kubernetes": "^0.9.1",

Follow updated installation steps https://backstage.io/docs/features/kubernetes/installation 

"@backstage/plugin-kubernetes" should be updated in topology plugin as well along with app and backend

<img width="1792" alt="image" src="https://github.com/janus-idp/backstage-plugins/assets/5129024/d543bb8c-3d52-4c4b-841e-8f996bf77042">
