### ISSUE TITLE
[Quay] The security scan should display a message when everything is good

### ISSUE THREAD

**Issue by christophe-f** [janus-idp/backstage-plugins#293]
Currently, the Quay plugin will show the number of issues when there are security vulnerabilities. But it's empty when there is no issue. 

<img width="1331" alt="Screenshot 2023-04-25 at 2 36 33 PM" src="https://user-images.githubusercontent.com/6601523/234400353-00458bbd-2c0d-447b-b63f-83623d7221e3.png">

To avoid confusion and think that something is not working, the plugin should display a message to indicate that there are no vulnerabilities. Similar to what Quay has. 

<img width="1373" alt="Screenshot 2023-04-25 at 2 36 56 PM" src="https://user-images.githubusercontent.com/6601523/234400711-fb01453f-39db-4d06-ac5a-883d248e6e17.png">

**Comment by tumido** [comment]
Pending PR: #298
