### ISSUE TITLE
🔌 Plugin: OpenShift Dev Spaces

### ISSUE THREAD

**Issue by regicsolutions** [janus-idp/backstage-plugins#315]
### 🔖 Summary

When scaffolding a new repository with a Dev Spaces [Devfile](https://devfile.io/)  The dev-spaces-backend-plugin would provide a scaffolder action that would provision a new Dev Spaces Workspace for that repository and provide a link as output to the Dev Space. This is normally done manually in the UI:

![IMG_0573](https://user-images.githubusercontent.com/6157895/235590154-15939b37-3f6a-442a-9217-540b3a7a298e.jpeg)

The dev-spaces front end plugin would just provide a overview card similar to the [Lambda Plugin](https://github.com/RoadieHQ/roadie-backstage-plugins/blob/main/plugins/frontend/backstage-plugin-aws-lambda/README.md) instead of showing a view logs link, there would be a link called ‘Go to Dev Space’

It would also be neat to have a ’Back to IDP’ button in Visual Studio Code using some sort of shortcut extension. 

### 🌐 Project website (if applicable)

https://access.redhat.com/documentation/en-us/red_hat_openshift_dev_spaces/3.1/html/user_guide/introduction-to-devfile#

### ✌️ Context

This plugin would integrate Backstage with OpenShifts Cloud Based IDE Dev Spaces providing engineers with a single entry point to provision a new service and Dev Space using a golden path software template.

### 👀 Have you spent some time to check if this plugin request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by viniciusfcf** [comment]
Actually most repositories could be opened in Dev Spaces using the URL: https://<openshift_dev_spaces_fqdn>#<git_repository_url>.

What I imagine to this plugin was list the last opened workspaces. The developer does not need to remember what project he used yesterday or last week, it will be listed.
