### ISSUE TITLE
🐛 Tekton plugin - Latest pipeline run card is too small

### ISSUE THREAD

**Issue by serenamarie125** [janus-idp/backstage-plugins#316]
**Describe the bug**
When clicking on the CI/CD tab, the `Latest Pipeline Run` card is not wide enough
see screenshot below

**To Reproduce**

1. Go to 'CI/CD tab' to view Latest Pipeline Run card
2. See issue

**Expected behavior**
Expectation is that the card should be 100% of the width of the screen.

**Screenshots**

![Screenshot 2023-05-02 at 10 14 42 AM](https://user-images.githubusercontent.com/12504403/235700995-8a622f14-e56c-464a-ada2-127315091a9a.png)

**Comment by christophe-f** [comment]
It was missing the wrapper `<Grid item md={12} xs={12}>` in the page. The plugin is fine.
