### ISSUE TITLE
🐛 Tekton plugin - Old PLRs don't have correct status in the Pipeline Runs table

### ISSUE THREAD

**Issue by serenamarie125** [janus-idp/backstage-plugins#319]
**Describe the bug**
When properly annotating resources, the old PLR are not showing the appropriate status.

Is additional information needed in the README?  Or is this a bug? 

**To Reproduce**

**Expected behavior**
Expectation is that the information in Backstage would match what's shown in OpenShift 

**Screenshots**
Backstage -> TEKTON tab (note this was taken when the most recent PL was still running)
![Screenshot 2023-05-02 at 10 14 17 AM](https://user-images.githubusercontent.com/12504403/235704260-b43c21cb-161e-42df-9fea-a63872560596.png)

OpenShift Console - PLR list (note this was taken once all 3 were successful)
![Screenshot 2023-05-02 at 10 56 35 AM](https://user-images.githubusercontent.com/12504403/235704593-cded7f0a-7eb9-4d46-b0f3-1fec6c626928.png)

**Additional context**

**Comment by invincibleJai** [comment]
did we add the required labels on Pipeline and then started the Pipeline? or were the labels added later only to PipelineRun?

If the pipeline has labels and we do a rerun then labels get propagated to PipelineRuns and taskRuns and both would be in sync 

Can you check if taskRuns has the required annotations?

**Comment by debsmita1** [comment]
Closing this ticket as it is not reproducible anymore. Please feel free to re-open this or create a new one if you see this issue.
