### ISSUE TITLE
Create a standalone dev environment for plugins that depend on catalog

### ISSUE THREAD

**Issue by tumido** [janus-idp/backstage-plugins#330]
While we already have a standalone dev environments backend plugins serving their own API endpoints, we're lacking a setup that would allow us to work against a Backstage catalog. Currently the only way how to see if entities are being properly discovered and ingested is to stand up `packages/backstage` and connect the plugin to it. This is not suitable if we want to isolate each plugin into separate dev environments.

~This currently blocks #324. If merged, we have no way to develop *keycloak*, *3scale*, *ocm*, plugins.~

- [x] Keycloak backend has a standalone dev environment - solved via https://github.com/janus-idp/backstage-plugins/pull/543
- [x] #600
- [x] #601
- [x] #602
- [x] #603

**Comment by nickboldt** [comment]
Relevant downstream issue: https://issues.redhat.com/browse/RHIDP-32
