### ISSUE TITLE
Create Scaffolder Action to run Ansible playbook

### ISSUE THREAD

**Issue by joshgav** [janus-idp/backstage-plugins#332]
**Is your feature request related to a problem? Please describe.**
I don't have a graphical interface for non-technical users to easily run Ansible playbooks.

**Describe the solution you'd like**
I want to publish Ansible playbooks via a web UI for users to provide a few parameters and run with a click.

**Describe alternatives you've considered**
- Use Ansible's Automation Services Catalog, but this [is deprecated](https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.3/html/getting_started_with_automation_services_catalog/pr01) and will be removed in the next version.
- Publish these actions via ServiceNow, but developers would prefer Backstage.

**Additional context**
This was requested by an enterprise that uses Ansible for automation and discussed with @serenamarie125 @cooktheryan and @scdaniels

**Comment by tumido** [comment]
Hi @joshgav, can you please check if there's an overlap with https://github.com/janus-idp/backstage-plugins/issues/189 ? If we're converging to the same solution, we may be able to close one of the issues as duplicate. 🙂

**Comment by joshgav** [comment]
Hi @tumido, I don't think they're quite the same but I'd like to do a bit of research before replying and hopefully clarify my ask. Thanks!

**Comment by cooktheryan** [comment]
@joshgav were you thinking of running playbooks with AAP or without?

**Comment by joshgav** [comment]
With AAP. I'd like to point to an existing playbook registered in AAP and use its vars as fields in a Backstage template. Then when I click "Run" it would run that one-off task.

Thinking about it, it actually it wouldn't render any templates, just invoke an Ansible playbook.

**Comment by joshgav** [comment]
I'd like to explicitly contrast this request with the scaffolder template to run a job here: <https://github.com/janus-idp/software-templates/tree/main/scaffolder-templates/ansible-job>

That template renders a Kubernetes CR to invoke a job and writes it to a git repo, which is reasonable for GitOps-style long-term configuration. But this issue asks for the ability to invoke a job on demand without persisting it anywhere. It probably should be done by directly calling an Ansible API.

**Comment by cooktheryan** [comment]
@tumido @joshgav this may end up being a wall of text but hopefully it explains where I think we can go. So right now there is a PR that lists job templates within AAP. This func could be extended to list jobs within AAP as it would just be an additional API call and labeling within the catalog. How I believe that we could do this sooner than later would be the following.


* Create or use a custom Action(https://backstage.io/docs/features/software-templates/writing-custom-actions) that can make an API call
* Using GPT we prompt the user to provide their API token for Ansible which we then feed into the custom action
* Within the GPT we allow for people to specify variables to pass when we build out the API call similar to this (https://github.com/janus-idp/software-templates/pull/133/files#diff-1ed065ce4dd5b7a4c50940efc6f72ec4d31006b0a462d6819162dd9779be013aR50-R56)
* User clicks create then the action runs. The difficult part of this process is recording the status after a run will have occured

**Comment by joshgav** [comment]
@cooktheryan a custom action to invoke the Ansible API with the parameters from a template as the vars values would be great, yes. :tada:

Also yes, it would be great to list the job runs. That could be a way for users to _observe_ job runs too - for example, after triggering the action we could redirect the browser to the JobRuns view. It would also parallel the Tekton plugin which focuses on PipelineRuns as opposed to Pipelines.

As we've been chatting today I realized it would be nice for users to be able to invoke a one-off job straight from the _Job Template_ entity page, as it seems that's where a user would actually discover them. Something to think about.
