### ISSUE TITLE
🔌 Plugin: Matomo Plugin for the Website Type

### ISSUE THREAD

**Issue by riginoommen** [janus-idp/backstage-plugins#360]
### 🔖 Summary

The Matomo plugin will enable website analytics and tracking capabilities within Backstage, allowing organizations to gather valuable insights about their website usage. 

### 🌐 Project website (if applicable)

https://matomo.org/

### ✌️ Context

**Basic Required Features with Plugin**

The plugin should integrate seamlessly with the existing Backstage framework, providing an intuitive user interface for matomo data. Key features to consider for this plugin include:

1) Visit Summary

2) Visits Over Time

3) Avg Time On Site

4) Bounce Rate

5) Actions/Visit

6) User Action Overview

7) Visit By Page URL

8) Time By Page URL

9) Visit Geography Overview

10) Visit Device Overview

This will also help Janus IDP to Promote the analytics pillar

 **Acceptance Criteria**
The Matomo plugin is developed as a separate package and can be easily added to a Backstage installation.
Users can configure the Matomo tracking code or site ID within the Backstage settings.

### 👀 Have you spent some time to check if this plugin request has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes, I am willing to submit a PR!

**Comment by riginoommen** [comment]
Screenshot 1

<img width="1904" alt="image" src="https://github.com/janus-idp/backstage-plugins/assets/3840244/b503778a-12aa-44b7-9329-00dbf4d9ca83">

Screenshot 2

<img width="1904" alt="image" src="https://github.com/janus-idp/backstage-plugins/assets/3840244/a170f1d7-a8f1-4632-b1c7-985ffe0f09d5">

Screenshot 3

![Uploading image.png…]()

**Comment by npatil9** [comment]
> developer portal usage
Replace with Website usage.

**Comment by serenamarie125** [comment]
This looks like a great addition, and there is also an [open issue](https://github.com/backstage/backstage/issues/15644) in upstream Backstage requesting something similar!
