### ISSUE TITLE
Create a common package for common hooks, utils, and components that can be used by multiple plugins

### ISSUE THREAD

**Issue by debsmita1** [janus-idp/backstage-plugins#448]
**Is your feature request related to a problem? Please describe.**
There are multiple hooks, utils, and components that are duplicated in various plugins.

**Describe the solution you'd like**
Create a common package containing the utils, hooks and components which be used by the different plugins

**Describe alternatives you've considered**
To be decided

**Additional context**

**Comment by tumido** [comment]
So.. I did a bit of investigation on this topic and it seems we have only a single option available to us anyways - to create and publish 2 new packages that would contain this common code.

Let's create:
- [ ] 1 package for frontend code (`@janus-idp/shared-react`)
   - [ ] Table component
   - [ ] OCI image tags etc.
   - [ ] Utils from
      - https://github.com/janus-idp/backstage-plugins/blob/main/plugins/quay/src/lib/utils.ts
      - https://github.com/janus-idp/backstage-plugins/tree/main/plugins/topology/src/utils
      - and alike..
   - [ ] Common hooks 
- [ ] 1 package for backend code (`@janus-idp/shared-node`) - **Doesn't seem like we need this one at this point**

If anybody has any better ideas on package names or would like to extend the list of content included, please post them here. 🙂

**Comment by invincibleJai** [comment]
> So.. I did a bit of investigation on this topic and it seems we have only a single option available to us anyways - to create and publish 2 new packages that would contain this common code.
> 
> Let's create:
> 
> * [ ]  1 package for frontend code (`@janus-idp/shared-react`)
>   
>   * [ ]  Table component
>   * [ ]  OCI image tags etc.
>   * [ ]  Utils from
>     
>     * https://github.com/janus-idp/backstage-plugins/blob/main/plugins/quay/src/lib/utils.ts
>     * https://github.com/janus-idp/backstage-plugins/tree/main/plugins/topology/src/utils
>     * and alike..
>   * [ ]  Common hooks
> * [ ]  1 package for backend code (`@janus-idp/shared-node`) - **Doesn't seem like we need this one at this point**
> 
> If anybody has any better ideas on package names or would like to extend the list of content included, please post them here. 🙂

This sounds good to me as part of this ticket we can create just the package for frontend and then start with moving/refactoring common types/hooks/utils/components moved as part of this PR https://github.com/janus-idp/backstage-plugins/pull/447 (which has duplication) and we can have other ticket needed to iteratively add more to it.

@tumido / @debsmita1 does this makes sense?

**Comment by tumido** [comment]
Yes, makes perfect sense. Let's start with an empty package and start gradually transferring/unifying duplications there. It doesn't need to happen over night or via a single PR. We can slowly start working towards that.
