### ISSUE TITLE
JFrog Artifactory Plugin broken

### ISSUE THREAD

**Issue by timdittler** [janus-idp/backstage-plugins#450]
**Describe the bug**
The query the plugin sends to Artifactory always receives a 404 reply.

**To Reproduce**

1. Install the plugin
2. Add anything to components
3. The Artifactory tab is always empty

**Expected behavior**
A list of docker images should be shown

**Additional context**
The plugin [filters for packageId](https://github.com/janus-idp/backstage-plugins/blob/main/plugins/jfrog-artifactory/src/api/index.ts#L63), which is not documented and unavailable in [PackageFilter of GraphQL API](https://jfrog.com/help/r/jfrog-rest-apis/graphql).

**Comment by seb2020** [comment]
Hi,
I have the same issue. Is there a fix ?
