### ISSUE TITLE
Reminder: Upgrade keycloak client once Backstage supports ESM

### ISSUE THREAD

**Issue by tumido** [janus-idp/backstage-plugins#47]
Keycloak admin client drops support for CommonJS by `v19`. It's ESM only, causing headaches to many folks:
https://github.com/keycloak/keycloak-nodejs-admin-client/issues/523

However the decision is that they won't introduce CommonJS back. Our only hope is for Backstage to fully support ESM.

https://github.com/backstage/backstage/issues/7011
https://github.com/backstage/backstage/issues/8242
https://github.com/backstage/backstage/issues/12218

Related:
- [ ] https://github.com/janus-idp/backstage-plugins/pull/46
- [ ] https://github.com/janus-idp/backstage-plugins/pull/50
- [ ] https://github.com/janus-idp/backstage-plugins/pull/147
- [ ] https://github.com/janus-idp/backstage-plugins/pull/518

**Comment by nickboldt** [comment]
@davidfestal FYI

**Comment by davidfestal** [comment]
This would depend on the Dynamic backend plugin loading feature supporting ESM modules, which is proably not the case now. It has not even be investigated or tested.

**Comment by 04kash** [comment]
Closing this as upgrading keycloak client is being tracked under this epic: https://issues.redhat.com/browse/RHIDP-1645.
