### ISSUE TITLE
🔌 Plugin: AAP (Ansible)

### ISSUE THREAD

**Issue by serenamarie125** [janus-idp/backstage-plugins#481]
## Goal
Programmatically populate the Backstage catalog with job templates from your AAP instance.

### What problem does this solve?
Although there is a GPT to run a Job Template, there is no way to discover what Job Templates can be run, or what they do from within Backstage.
 
### Use cases
_Details to follow_

### Acceptance criteria
_Details to follow_

## Issues in Epic
- https://github.com/janus-idp/backstage-plugins/issues/528
- https://github.com/janus-idp/backstage-plugins/issues/522
- https://github.com/janus-idp/backstage-plugins/issues/652
- https://github.com/janus-idp/backstage-plugins/issues/545
- https://github.com/janus-idp/backstage-plugins/issues/546

**Comment by joshgav** [comment]
Could we make it possible to invoke a one-off run of the playbook from its entity page? I have a customer who seeks the ability to invoke a playbook from the Backstage UI.

This is related to https://github.com/janus-idp/backstage-plugins/issues/332 - if we could invoke a playbook from its entity page perhaps a Scaffolder action wouldn't be needed.

**Comment by invincibleJai** [comment]
> Could we make it possible to invoke a one-off run of the playbook from its entity page? I have a customer who seeks the ability to invoke a playbook from the Backstage UI.
> 
> This is related to #332 - if we could invoke a playbook from its entity page perhaps a Scaffolder action wouldn't be needed.
> 
> Also note that the template for running an Ansible job [here](https://github.com/janus-idp/software-templates/tree/main/scaffolder-templates/ansible-job) doesn't directly invoke the job; rather it creates a Kubernetes CRD describing the job run and writes it to a "GitOps" repo. My ask is for a way to directly invoke the job without Kubernetes or GitOps, just Ansible.

This epic was scoped to list job templates in the software catalog and subsequently, we need to plan more features for the plugin for AAP.

@sonyccd / @Kasturi1820 / @cooktheryan FYI

**Comment by cooktheryan** [comment]
there would need to be a host or container that would actually launch the playbook. With that host we would need to have credentials to connect to the object. This could be generally created but the ansible-playbook would have to run from a job pod which I'm not sure if that is completely supported from RH.

It may be worth talking with Christian Adams, Roger Lopez, or even someone like Sean Cavanaugh who would have insights with interacting with different components

**Comment by invincibleJai** [comment]
Closing it as all linked tasks are in close state
