### ISSUE TITLE
🔌 Plugin: Keycloak v2

### ISSUE THREAD

**Issue by serenamarie125** [janus-idp/backstage-plugins#482]
## Goal
_Details to follow_

### What problem does this solve?
_Details to follow_
 
### Use cases
_Details to follow_

### Acceptance criteria
_Details to follow_

## Issues in Epic
- https://github.com/janus-idp/backstage-showcase/issues/382

**Comment by rtaniwa** [comment]
@tumido as I understand it, this was opened specifically to pull in this [PR](https://github.com/janus-idp/backstage-plugins/pull/432), which it looks like you are going to pick up to finalize. As such I will assign you as epic owner. If there are doc changes and QE re-testing required, please create some stories for those stakeholders to track that work.

**Comment by rtaniwa** [comment]
Can we make sure we create sub-stories for doc and QE if they will be required to make changes or additional test coverage as a result of this change?
