### ISSUE TITLE
When authmiddleware is setup for any backstage-plugin, project will not authenticate

### ISSUE THREAD

**Issue by pbuehl-redhat** [janus-idp/backstage-plugins#486]
**Describe the bug**
Projects utilizing the quay backstage plugins will not work with authmiddleware set up

**To Reproduce**

1. Go to 'packages/backend/index.ts'
2. Set up apirouter for one of the plugins i.e. 'apiRouter.use('/quay', authMiddleware, await quay(quayEnv));'
3. run backstage instance and see that authentication will fail

**Expected behavior**
Projects will be allowed to authenticate when using authmiddleware.

**Comment by tumido** [comment]
Hi @pbuehl-redhat thank you for noticing this, filing an issue and even opening a pull request. 👍  That's huge help. I think this is an important issue to fix. 🙂

**Comment by tumido** [comment]
@pbuehl-redhat please ignore my comment above. I finally did my homework 🙂 

https://github.com/janus-idp/backstage-plugins/pull/498#discussion_r1273380327

All is good, your PR is good.

**Comment by pbuehl-redhat** [comment]
thanks @tumido
