### ISSUE TITLE
🔌 Plugin: Scorecard, v1

### ISSUE THREAD

**Issue by serenamarie125** [janus-idp/backstage-plugins#495]
## Goal
_Details to follow_

### What problem does this solve?
_Details to follow_
 
### Use cases
_Details to follow_

### Acceptance criteria
_Details to follow_

## Issues in Epic
_Details to follow_

**Comment by kadel** [comment]
@jasperchui @rtaniwa @christophe-f Any idea what this is about?

**Comment by kadel** [comment]
@rtaniwa thank you for the context. I'm closing this for now.
