### ISSUE TITLE
ocm-backend 2.1.4 makes ocm a blank page on Dev Preview 0.1

### ISSUE THREAD

**Issue by josephca** [janus-idp/backstage-plugins#496]
When running multi cluster plugins with the following versions on Dev Preview 0.1:

ocm-backend 2.1.4
ocm-common 2.0.2
ocm 2.2.9

- ocm-backend 2.1.4 makes ocm a blank page on Dev Preview 0.1.
- ocm-backend 3.0.2 worked.

cc: @schultzp2020 @PatAKnight

**Comment by tumido** [comment]
My question is, why would you do that? You should not mix different plugin versions... Why would you mix a dated `ocm-backend` version with a newer `ocm` one? Do we claim we support multiple versions of the `ocm-backend` plugin with different set of versions of `ocm` plugin?

**Comment by josephca** [comment]
There was confusion and updates on supported plugin versions. Closing this issue.
