### ISSUE TITLE
ocm plugins on Backstage 1.13 and older Backstage is failed

### ISSUE THREAD

**Issue by josephca** [janus-idp/backstage-plugins#497]
When running multi cluster plugins with the following versions on Backstage 1.13:

ocm-backend 3.0.3
ocm-common 2.1.0
ocm 3.0.2

copying comment from @schultzp2020
@backstage/backend-common package that we have been unable to track down on backstage versions older than 1.14.0. This issue only seems to impact keycloak-backend and ocm-backend. It does not seem to impact argo-cd-backend. I have tried to track down the dependency differences; however, the two dependencies (@backstage/backend-tasks and @backstage/catalog-model) that are common between keycloak-backend and ocm-backend and not argo-cd-backend haven't been updated since backstage version 1.13.0. So, that rules out the above two dependencies.

**Comment by schultzp2020** [comment]
https://github.com/janus-idp/backstage-plugins/issues/500
