### ISSUE TITLE
README issues

### ISSUE THREAD

**Issue by schultzp2020** [janus-idp/backstage-plugins#499]
## `ocm`

- `Setting up the OCM backend package` `5` `ii`: codeblock title needs to be updated to `packages/backend/src/plugins/catalog.ts`
- `Setting up the OCM frontend package` `2` `2`: codeblock highlighting should include `isType` function and the entirety of `resourcePage`

## `quay`

- `Configuration` `2`: codeblock highlight should include `<EntityPageLayout.Route />` closing tag

## `topology`

- The text above the third codeblock: `customResources` is missing a space before the inline codeblock

**Comment by lokeshrangineni** [comment]
I'm planning to work on it.

**Comment by schultzp2020** [comment]
@lokeshrangineni any update?
