### ISSUE TITLE
🔌 Plugin: ROSA

### ISSUE THREAD

**Issue by serenamarie125** [janus-idp/backstage-plugins#509]
## Goal
As a user of Backstage, show all ROSA clusters in the Backstage catalog.  
 
### Acceptance criteria
- ROSA clusters should be available in the Backstage catalog.
- Users should be able to see the current cluster status 
- When looking at the cluster detail page, users should be able to see cluster details, including 
 - OpenShift Console link
 - OCP & Kubernetes versions
 
## Issues in Epic
_Details to follow_

**Comment by schwesig** [comment]
ack

**Comment by serenamarie125** [comment]
Trying to remain aligned with the Multi cluster view, here's the Cluster list
<img width="1440" alt="ROSA Clusters (1)" src="https://github.com/janus-idp/backstage-plugins/assets/12504403/9f3b8bfb-2704-4908-9a34-1b7c6ec55d45">

And the cluster details
<img width="1440" alt="ROSA - Cluster Details (1)" src="https://github.com/janus-idp/backstage-plugins/assets/12504403/e1f0051c-6900-422b-bfca-f0f90266c51b">
