### ISSUE TITLE
Keycloak - more flexibility at import time

### ISSUE THREAD

**Issue by paoloantinori** [janus-idp/backstage-plugins#511]
**Is your feature request related to a problem? Please describe.**
I've configured successfully the Backstage Plugin to communicate with RH SSO 7.6.2.GA .
In the KC realm we are using we have enabled Github as an IdP provider.
Unfortunately, the default mapping uses Github emails as userid.
And an e-mail is not an acceptable identifier for Backstage:

```
2023-07-05T16:48:11.901Z catalog warn Policy check failed for user:default/paolo.antinori@gmail.com; caused by Error: "metadata.name" is not valid; expected a string that is sequences of [a-zA-Z0-9] separated by any of [-_.], at most 63 characters in total but found "paolo.antinori@gmail.com". To learn more about catalog file format, visit: https://github.com/backstage/backstage/blob/master/docs/architecture-decisions/adr002-default-catalog-file-format.md type=plugin entity=user:default/paolo.antinori@gmail.com
```

**Describe the solution you'd like**
Assuming that using an external IdP in Keycloak is a pretty common use-case, I'm looking for ways to bypass this issue.
Ideally the Keycloak Backstage plugin could be extended with some pre-defined strategy to clean data to accept only Backstage compatible values. Even better if I could provide directly a javascript lambda, where I can specify my own custom cleaning logic.

**Describe alternatives you've considered**
As a mitigation, I think that KC should be able to be instructed to use a different convention, but I think it might still be valuable to have this feature present also on the Backstage plugin side.
I'm right now asking the KC engineers what would be the correct way to mitigate this problem on the Keycloak side, since all my attempts failed so far.

**Comment by paoloantinori** [comment]
This is the potential bug on Keycloak preventing to mitigate this issue on its side: https://github.com/keycloak/keycloak/issues/11195

**Comment by tumido** [comment]
Hi @paoloantinori yes, I think we want to enable this behavior.

We want users to be able to use `userTransformer` and `groupTransformer` functions that allow them to mutate the objects before their ingestion into Catalog.

This should satisfy similar needs as described for example here in LDAP plugin docs:

https://backstage.io/docs/integrations/ldap/org/#customize-the-provider

Do you think such a feature can help you with this problem? Or are you looking for a different solution?

There's a PR from the community introducing something like this, however, it still requires a lot of changes to reduce hardcoded behavior and offer the necessary customizations we strive for: https://github.com/janus-idp/backstage-plugins/pull/432
