### ISSUE TITLE
[ACR Plugin] QE for ACR plugin

### ISSUE THREAD

**Issue by invincibleJai** [janus-idp/backstage-plugins#526]
# Description: 

Test ACR plugin and update test plan

# Acceptance Criteria:

- [x]  Test Plan

**Comment by josephca** [comment]
Hi @invincibleJai, 
Please review e2e test case. Thanks, 

OCI Registry (ACR) plugin install and verification ([readme/instruction](https://github.com/janus-idp/backstage-plugins/blob/main/plugins/acr/README.md))

**Prereqs**:

1) setup instance of ACR server and obtain an authorization token

**OCI Registry (ACR) plugin install and verification:**

2) install @janus-idp/backstage-plugin-acr plugin and enable it
3) start backstage and navigate to the ACR tab for a component with the 'azure-container-registry/repository-name' annotation
4) navigate to the ACR tab and check if you can view the tags, last update and Manifest (SHA) of an image related to a catalog deployed by an image in the Azure Container Registry
5) test the table to see if moving to next/prev/first/last page works
6) test the table filtering/sorting functionality and page size

**Comment by invincibleJai** [comment]
> Hi @invincibleJai, Please review e2e test case. Thanks,
> 
> OCI Registry (ACR) plugin install and verification ([readme/instruction](https://github.com/janus-idp/backstage-plugins/blob/main/plugins/acr/README.md))
> 
> **Prereqs**:
> 
> 1. setup instance of ACR server and obtain an authorization token
> 
> **OCI Registry (ACR) plugin install and verification:**
> 
> 2. install @janus-idp/backstage-plugin-acr plugin and enable it
> 3. start backstage and navigate to the ACR tab for a component with the 'azure-container-registry/repository-name' annotation
> 4. navigate to the ACR tab and check if you can view the tags, last update and Manifest (SHA) of an image related to a catalog deployed by an image in the Azure Container Registry
> 5. test the table to see if moving to next/prev/first/last page works
> 6. test the table filtering/sorting functionality and page size

@josephca yeah this looks good
