### ISSUE TITLE
🔌 Plugin: Cloud-Image-Directory

### ISSUE THREAD

**Issue by miyunari** [janus-idp/backstage-plugins#534]
### 🔖 Summary

The Cloud-Image-Directory lists, processes and filters (currently only RHEL) images from different cloud providers, to make it easier to find the right image. 

I think the plugin would be in the same direction as the Quay plugin and OpenShift Image Registry plugin. 

The screens would be similar to https://staging.imagedirectory.cloud/.

### 🌐 Project website (if applicable)

repository: https://github.com/redhatcloudx/transformer/
website: https://imagedirectory.cloud/
swagger (we would use v2 for the plugin, currently work in progress): https://imagedirectory.cloud/swagger/index.html

### 👀 Have you spent some time to check if this plugin request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by tumido** [comment]
@christophe-f @sonyccd wdyt? Would such plugin make sense to a Backstage user?

I'm thinking that a screen allowing you quickly standup RHEL in the cloud of your choice would be useful.

Additionally, we can also think about making this a resource provider for the catalog, so we can offer these instance-type options as a dropdown in GPTs, wdyt?

**Comment by christophe-f** [comment]
Yes this should be a GPT as that where users can create anything. A user would be able to select an image and start the process.
After it can be registered as a resource in the catalog. For this specific type of resource, we could have a plugin to show specific information like quota, usage, etc

**Comment by miyunari** [comment]
May I ask, what is a GPT? :)

**Comment by tumido** [comment]
@miyunari GPTs (Golden Path Templates), also known as Software Templates. You can learn more about them here:

https://backstage.io/docs/features/software-templates/

It's basically a self-service workflow that allows people to accomplish many tasks, from bootstraping a new git repo for Python application (or any other application), to requesting a namespace on a specific kubernetes cluster and deploying to that through ArgoCD... Basically any self-service task you can imagine a developer goes through can be automated via this.

We have some sample templates available here:
https://showcase.janus-idp.io/create?filters%5Bkind%5D=template&filters%5Buser%5D=all

Their definitions:
https://github.com/janus-idp/software-templates
