### ISSUE TITLE
🔌  Plugin: Keycloak

### ISSUE THREAD

**Issue by serenamarie125** [janus-idp/backstage-plugins#54]
# Goal
This epic aims to develop a new Backstage UI plugin in the Janus repo.  This UI plugin should integrate Keycloak into Backstage to enable Keycloak user and group entities to be used in the standard Backstage catalog model.

## What problem does this solve?
Although Backstage contains the functionality to connect to external identity providers to enable authentication and apply proper RBAC, there is no integration point with Keycloak authentication today.

## Requirements
- Plugin
- Test plan
- Installation documentation
- End user documentation

## Issues in Epic
- [x] https://github.com/janus-idp/backstage-plugins/issues/86
- [x] #130
- [x] #307 

## Stakeholder sign-off
- [x] QE
- [x] Doc

**Additional context**

**Comment by lsharar** [comment]
@rtaniwa and @serenamarie125 all of the three tasks inside this issue appear complete.  Ok to close this issue as complete, and the associated Jira? 
Done https://github.com/janus-idp/backstage-plugins/issues/86
Done https://github.com/janus-idp/backstage-plugins/issues/130
Done https://github.com/janus-idp/backstage-plugins/issues/307
