### ISSUE TITLE
[AAP Plugin] QE for AAP plugin

### ISSUE THREAD

**Issue by invincibleJai** [janus-idp/backstage-plugins#545]
# Description: 

Test AAP plugin and update the test plan

# Acceptance Criteria:

- [x]  Test Plan

**Comment by josephca** [comment]
Hi @invincibleJai 
Please review e2e test case. Thanks, 

AAP (Ansible® Automation Platform) backstage provider plugin install and verification ([readme/instruction](https://github.com/janus-idp/backstage-plugins/blob/main/plugins/aap-backend/README.md))

**Prereqs**:

1) [setup instance of AAP](https://github.com/janus-idp/backstage-plugins/issues/528#issuecomment-1640133403) 
    1.a) Get an Openshift Container Platform (OCP) Cluster
    1.b) Search for the AAP operator in operatorHub and install it
    1.c) Create a Custom Resource for AutomationController with default values
    1.d) Go to the "aap" namespace and go to the Topology View
    1.e) Click on the workload "XXX-web", open the public route. This will take you to the AAP instance, where you get the subscription for it
    1.f) Once subscription is obtained, go to the AAP dashboard, click on Templates under resources and add a new template
    1.g) Get the token: click on user details on right and then on the token. Generate a token

**AAP plugin install and verification**:

2) install AAP plugin and enable it
3) start backstage and verify AAP plugin populated the software catalog with job templates from the configured AAP ins

**Comment by invincibleJai** [comment]
> Hi @invincibleJai Please review e2e test case. Thanks,
> 
> AAP (Ansible® Automation Platform) backstage provider plugin install and verification ([readme/instruction](https://github.com/janus-idp/backstage-plugins/blob/main/plugins/aap-backend/README.md))
> 
> **Prereqs**:
> 
> 1. [setup instance of AAP](https://github.com/janus-idp/backstage-plugins/issues/528#issuecomment-1640133403)
>    1.a) Get an Openshift Container Platform (OCP) Cluster
>    1.b) Search for the AAP operator in operatorHub and install it
>    1.c) Create a Custom Resource for AutomationController with default values
>    1.d) Go to the "aap" namespace and go to the Topology View
>    1.e) Click on the workload "XXX-web", open the public route. This will take you to the AAP instance, where you get the subscription for it
>    1.f) Once subscription is obtained, go to the AAP dashboard, click on Templates under resources and add a new template
>    1.g) Get the token: click on user details on right and then on the token. Generate a token
> 
> **AAP plugin install and verification**:
> 
> 2. install AAP plugin and enable it
> 3. start backstage and verify AAP plugin populated the software catalog with job templates from the configured AAP ins

Thanks @josephca, yeah this looks good to me.
