### ISSUE TITLE
App Topology: Documentation for Topology plugin

### ISSUE THREAD

**Issue by divyanshiGupta** [janus-idp/backstage-plugins#548]
# Description: 

Review the README for the Topology plugin and update/create new docs as needed

# Acceptance Criteria:

- [ ]  Installation documentation
- [ ]  End user documentation

**Comment by hmanwani-rh** [comment]
Topology plugin doc updates are completed with the following JIRAs:

https://issues.redhat.com/browse/RHIDP-209
https://issues.redhat.com/browse/RHIDP-200

Therefore, closing this issue.
