### ISSUE TITLE
[Tekton]: QE for Tekton plugin

### ISSUE THREAD

**Issue by divyanshiGupta** [janus-idp/backstage-plugins#551]
# Description: 

Test Tekton plugin and update the test plan

# Acceptance Criteria:

- [x]  Test Plan

**Comment by josephca** [comment]
Hi @divyanshiGupta, 

Please review the test case below. Thanks!

**Prereqs** ([readme/instruction](https://github.com/janus-idp/backstage-plugins/blob/main/plugins/tekton/README.md)):

1) Install kubernetes plugins (@backstage/plugin-kubernetes and @backstage/plugin-kubernetes-backend)
2) configure Kubernetes plugin and connects to the cluster using a ServiceAccount

**Tekton plugin install and verification:**

3) install tekton plugin and enable it
4) open backstage application and select a component from the catalog page
5) go to the CI/CD tab  
6) verify CI/CD tab displays the latest PipelineRun resources associated to a Kubernetes cluster. The resource includes tasks to complete
7) hover the mouse pointer on a task card and check the steps to complete
8) click 'GO TO TEKTON' option at the bottom and check it redirects you to the TEKTON tab
9) from TEKTON tab, check pipeline runs related to the cluster. 
10) verify if moving to next/prev/first/last page works in the pipeline runs list page 
11) click on the Task Status bar of a pipelinerun in the pipelinerun list to open a modal
12) verify the modal has a list of tasks on the left and the corresponding task logs on the right
13) verify that clicking on a PipelineRun in the PipelineRun list opens the PipelineRun visualization

**Comment by debsmita1** [comment]
> Hi @debsmita1,
> 
> Please review the test case below. Thanks!
> 
> **Prereqs** ([readme/instruction](https://github.com/janus-idp/backstage-plugins/blob/main/plugins/tekton/README.md)):
> 
> 1. Install kubernetes plugins (@backstage/plugin-kubernetes and @backstage/plugin-kubernetes-backend)
> 2. configure Kubernetes plugin and connects to the cluster using a ServiceAccount
> 
> **Tekton plugin install and verification:**
> 
> 3. install tekton plugin and enable it
> 4. open backstage application and select a component from the catalog page
> 5. go to the CI/CD tab
> 6. verify CI/CD tab displays the latest PipelineRun resources associated to a Kubernetes cluster. The resource includes tasks to complete
> 7. hover the mouse pointer on a task card and check the steps to complete

you can click on a task bubble to view the pipeline run logs. It will open a modal showing the task logs of the task bubble the user selects on the Latest PipelineRun Visualization.

> 8. click 'GO TO TEKTON' option at the bottom and check it redirects you to the TEKTON tab
> 9. from TEKTON tab, check pipeline runs related to the cluster.
> 10. verify if moving to next/prev/first/last page works in the pipeline runs list page
> 11. click on the Task Status bar of a pipelinerun in the pipelinerun list to open a modal
> 12. verify the modal has a list of tasks on the left and the corresponding task logs on the right
> 13. verify that clicking on a PipelineRun in the PipelineRun list opens the PipelineRun visualization

**Comment by josephca** [comment]
@debsmita1 Thanks for the input. I updated the test case with your input.
