### ISSUE TITLE
Testing need for Plugin: OCI Registry (JFrog)

### ISSUE THREAD

**Issue by jasperchui** [janus-idp/backstage-plugins#558]

**Comment by josephca** [comment]
Hi @tumido 

Please review the e2e test case. Thanks, 

OCI Registry (JFrog) plugin install and verification ([readme/instruction](https://github.com/janus-idp/backstage-plugins/blob/main/plugins/jfrog-artifactory/README.md))

**Prereqs**:

1) setup instance of JFrog artifactory server

**OCI Registry (JFrog) plugin install and verification:**

2) install @janus-idp/backstage-plugin-jfrog-artifactory plugin and enable it
3) start backstage and goto a website component -> Artifactory (ensure component has the 'jfrog-artifactory/image-name' annotation
4) verify if you can view the image data from artifactory/JCR registry - version/repository/manifest/modified/size of an image 
5) test table filtering and navigation (next/prev/first/last page)

**Comment by josephca** [comment]
@tumido Can you review it please? thanks

**Comment by rnapoles-rh** [comment]
@josephca please close if done or move to milestone 4.

**Comment by josephca** [comment]
Closing the issue as we have the test plan
