### ISSUE TITLE
Refactor: Move duplicate code to `plugins/shared-react`

### ISSUE THREAD

**Issue by tumido** [janus-idp/backstage-plugins#580]
**Goal**
We've recently introduced a `plugins/shared-react` package to reduce code duplication and maintenance. Now we need to move all the code duplications into this package.

**What problem does this solve? Please describe.**
Duplicate code is not healthy. Shared code should live in a shared package so we don't have to fix bugs in many different places.

**Use cases**
Easier maintenance and less work for engineers in the long run.

**Acceptance criteria**
Reduce Code duplication below threshold.

https://sonarcloud.io/component_measures?metric=duplicated_lines&view=list&id=janus-idp_backstage-plugins

- [x] #581
- [x] #582
- [x] #599

**Additional context**
![image](https://github.com/janus-idp/backstage-plugins/assets/7453394/68003ad0-d096-47ea-bcf7-e81c7db18035)

**Comment by debsmita1** [comment]
All the associated tasks have been completed so closing this ticket.
