### ISSUE TITLE
Move `icons`, `debounce` from Tekton and Topology plugins to `plugin/shared-react`

### ISSUE THREAD

**Issue by tumido** [janus-idp/backstage-plugins#582]
Part of epic: https://github.com/janus-idp/backstage-plugins/issues/580

This mainly affects files for:
- `icons`
- `debounce`

Reference:
https://sonarcloud.io/component_measures?metric=duplicated_lines&view=list&id=janus-idp_backstage-plugins

https://sonarcloud.io/component_measures?metric=duplicated_files&view=list&id=janus-idp_backstage-plugins

**Comment by tumido** [comment]
Icons were not moved, only `debounce`. Reopening.

https://github.com/janus-idp/backstage-plugins/blob/main/plugins/topology/src/common/components/icons.tsx

https://github.com/janus-idp/backstage-plugins/blob/main/plugins/tekton/src/components/common/icons.tsx

**Comment by divyanshiGupta** [comment]
Logged a ticket https://github.com/janus-idp/backstage-plugins/issues/716 for refactoring `icons` to use MUI icons based on this converstaion - https://github.com/janus-idp/backstage-plugins/pull/715#discussion_r1317244432.
