### ISSUE TITLE
Reduce code smells in various plugins

### ISSUE THREAD

**Issue by tumido** [janus-idp/backstage-plugins#583]
**Goal**
We've seen an influx of code smells lately. We should attend to it and reduce their amount. This can be a good learning experience for people to learn about individual plugins and their internals.

**What problem does this solve? Please describe.**
Fewer errors, fewer potential bugs, fewer troubles.

**Use cases**
N/A

**Acceptance criteria**
Codesmells are reduced to `< 10`, currently we have `112`. Code smells should be addressed via a PR or explained why they should be dismissed as irrelevant.

https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&sinceLeakPeriod=true&id=janus-idp_backstage-plugins

- [x] #584
- [x] #585
- [x] #586
- [x] #587
- [x] #588
- [x] #589
- [x] #590
- [x] #591
- [x] #592
- [x] #593
- [x] #594
- [x] #595
- [x] #596
- [x] #597
- [x] #598

**Additional context**
N/A

**Comment by invincibleJai** [comment]
can we close this as all linked issues are closed and we can have a separate ticket to handle future code smells
