### ISSUE TITLE
Reduce code smells in 3scale plugin

### ISSUE THREAD

**Issue by tumido** [janus-idp/backstage-plugins#588]
Part of: #583

Investigate code smells in the Tekton plugin and fix them via a PR or explained why they should be dismissed as irrelevant.

See this plugin folder and respective code smells column here:
https://sonarcloud.io/code?id=janus-idp_backstage-plugins&selected=janus-idp_backstage-plugins%3Aplugins

**Comment by riginoommen** [comment]
i like to take this issue
