### ISSUE TITLE
🔌  Plugin: Environments

### ISSUE THREAD

**Issue by serenamarie125** [janus-idp/backstage-plugins#59]
## Goals
This epic aims to develop a new Backstage UI plugin in the Janus repo.  We want to look into the functionality from the Application Environments view in the OpenShift Developer Perspective of the console, when OpenShift GitOps is installed.  As part of this epic, we need to evaluate the features which could be brought in as a plugin, as well as if we need OpenShift GitOps installed, or if Argo is enough.  The following features should be evaluated to see if they can be included:
- App Env Details page including a high level overview of the status of the app as deployed in each env

### Lists all applications which are "managed by GitOps"
![Image](https://user-images.githubusercontent.com/12504403/217913710-52eb3dd3-5287-4719-8982-dd09429e469c.png)

### Provides a high level overview of the status of the application as it's deployed across each "environment"
I![Image](https://user-images.githubusercontent.com/12504403/217913713-fa5a378d-17d5-47a2-ba4b-a423b272d35f.png)

### [Dark mode] on the details page and also what happens when there are no commit details for an app
![Image](https://user-images.githubusercontent.com/12504403/217913711-e23441df-961f-4045-ad01-6f23587fa20f.png)

**Comment by taras** [comment]
One possibility here would be to create an integration with the Scaffolder. 

There are a few developments in this area that might be of interesting,

* KPT experimental plugin for Backstage - http://kpt.dev
* Kratix integration using Scaffolder - https://www.youtube.com/watch?v=wj5VaXYTvrg
* Embedded Scaffolder Workflow - https://github.com/backstage/backstage/issues/14706

It would be great to have a general way of creating PRs against YAML documents using the scaffolder.

**Comment by serenamarie125** [comment]
Note that I have changed this epic to be aligned with `Environments`

Created #162 to be aligned with what we want to deliver in our first milestone.

**Comment by serenamarie125** [comment]
Also moved this out to Milestone 2

**Comment by regicsolutions** [comment]
Wanted to add there is a [keptn](https://github.com/keptn-sandbox/backstage-plugin-keptn) plugin as well that provides a environment list with its state.
