### ISSUE TITLE
Reduce code smells in Segment plugin

### ISSUE THREAD

**Issue by tumido** [janus-idp/backstage-plugins#590]
Part of: #583

Investigate code smells in the Tekton plugin and fix them via a PR or explained why they should be dismissed as irrelevant.

See this plugin folder and respective code smells column here:
https://sonarcloud.io/code?id=janus-idp_backstage-plugins&selected=janus-idp_backstage-plugins%3Aplugins

**Comment by Zaperex** [comment]
Should we close this issue since the code smells are due to plugin's `createPlugin` being marked as deprecated, and we still want the plugin to be registered as a plugin?

**Comment by invincibleJai** [comment]
@Zaperex yeah this looks like it can be ignored, can we have a PR with below so that it doesn't show in code smell

`// NOSONAR - add relevant comment`

@tumido let us know if you have other thoughts

**Comment by tumido** [comment]
Hm... I actually think it would be even better to remove the `@deprecated` comment instead. Since it's actually not deprecated, we want that functionality. Would that remove the code smell?
