### ISSUE TITLE
Move OCI catalog utils to `plugins/shared-react`

### ISSUE THREAD

**Issue by tumido** [janus-idp/backstage-plugins#599]
Part of: #580 

Quay, Jfrog, OpenShift image registry all use an `utils.ts` file.

This is a duplicate code that should be removed/moved to `plugins/shared-react`.

Sample search results ⬇️
https://github.com/search?q=repo%3Ajanus-idp%2Fbackstage-plugins%20formatSize&type=code

**Please move all common functions, not just the one I've searched for here.**

**Comment by navinyashende** [comment]
Interested to work on this.
