### ISSUE TITLE
OCM backend needs a standalone dev environment

### ISSUE THREAD

**Issue by tumido** [janus-idp/backstage-plugins#600]
We need to provide a standalone dev environment for plugins that interact with backstage catalog so we can eventually remove `packages` folder and develop plugins independently.

Please take a look at the OCM backend plugin and implement a catalog backend similar to the implementation for Keycloak plugin https://github.com/janus-idp/backstage-plugins/pull/543

**Comment by Zaperex** [comment]
Do we want to have the `ocm` frontend to start up when we run the standalone dev environment or do we want to use `backstage-cli package start`?
