### ISSUE TITLE
AAP backend needs a standalone dev environment

### ISSUE THREAD

**Issue by tumido** [janus-idp/backstage-plugins#602]
We need to provide a standalone dev environment for plugins that interact with backstage catalog so we can eventually remove `packages` folder and develop plugins independently.

Please take a look at the AAP backend plugin and implement a catalog backend similar to the implementation for Keycloak plugin https://github.com/janus-idp/backstage-plugins/pull/543

**Comment by navinyashende** [comment]
Interested to work on this.

**Comment by navinyashende** [comment]
Any pointers on local setup of AAP? I tried for docker images and found one on registry.redhat.com which needs registry service account.

**Comment by invincibleJai** [comment]
> Any pointers on local setup of AAP? I tried for docker images and found one on registry.redhat.com which needs registry service account.

Hey thanks, can follow https://github.com/janus-idp/backstage-plugins/issues/545#issuecomment-1678060826

@cooktheryan do you have any other pointers for local setup?

**Comment by cooktheryan** [comment]
@invincibleJai the difficult part is that you would either need a vm locally or in the cloud for standalone AAP or an OpenShift cluster where AAP can be deployed. With AAP many instances can be installed in a cluster into different namespaces

**Comment by navinyashende** [comment]
@invincibleJai @cooktheryan Thanks for sharing the setup. For standalone dev environment, requiring a cluster seems to be a bit tedious requirement at this point. Can we install the operator in a shared environment like operate-first.io and use it as a public instance for dev setup?

**Comment by cooktheryan** [comment]
@navinyashende the compute with operate fist has been decommissioned. There exists a cluster specifically for Janus development deployed through ROSA where we should have the capabilities to deploy it into multiple namespaces. /cc @jasperchui

**Comment by navinyashende** [comment]
@invincibleJai Sure, Can we have a document for this setup as well? That would help others like me who are not aware of the complex stuff.
