### ISSUE TITLE
Kiali backend needs a standalone dev environment

### ISSUE THREAD

**Issue by tumido** [janus-idp/backstage-plugins#603]
We need to provide a standalone dev environment for plugins that interact with backstage catalog so we can eventually remove `packages` folder and develop plugins independently.

Please take a look at the Kiali backend plugin and implement a catalog backend similar to the implementation for Keycloak plugin https://github.com/janus-idp/backstage-plugins/pull/543

**Comment by gashcrumb** [comment]
While replicating the dev environment locally I thought a good approach here would be to try getting this all running on `kind` to see if that will be a workable footprint.  This approach still may require some kind of setup script and more dependencies than I'd like, but we'll see.

It could also be just as feasible to capture some live data from the actual app and use that to drive a mock backend for the kiali plugin to fetch data from, provided that it's easy enough to add additional use cases in the future.

**Comment by gashcrumb** [comment]
Took a bit but I have an istio with Kiali and the sample app running on kind locally, next steps is to review my list of commands and see how much can be automated.  This approach requires `kubectl`, `kind`, `istioctl` and either docker or podman.  With this all running the control plane container is using ~6.5gb memory, I've seen worse :smile:
