### ISSUE TITLE
Chore(JFrog Artifactory): remove `<component-name>.defaultProps`

### ISSUE THREAD

**Issue by schultzp2020** [janus-idp/backstage-plugins#617]
## Work

Replace `<component-name>.defaultProps` with [default parameters](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters) because `defaultProps` has been [deprecated](https://github.com/jsx-eslint/eslint-plugin-react/issues/2396).

**Comment by anilabhabaral** [comment]
Please assign @schultzp2020
