### ISSUE TITLE
chore(plugins): remove unnecessary `useState`s when using `useAsync`

### ISSUE THREAD

**Issue by schultzp2020** [janus-idp/backstage-plugins#622]
## Work

Instead of using `useState` to handle state returned from `useAsync` we can destructure another value returned from `useAsync` called `value`. This would allow us to remove unnecessary `useState`s when dealing with `useAsync`.

e.g.
```tsx
// value's type is automatically inferred from the async callback return
const { loading, value } = useAsync(async () => {
    const { data } = await fetchData()
    
    return data;
  });
```

**Comment by AayushSaini101** [comment]
Please assign

**Comment by Zaperex** [comment]
Reopens because the PR that closed this only removed unnecessary `useState`s for the OCM plugin
