### ISSUE TITLE
keycloak-backend plugin: Compromised token in the ErrorLog

### ISSUE THREAD

**Issue by vargaadam** [janus-idp/backstage-plugins#629]
**Describe how is our service vulnerable**
In the `keycloak-backend` plugin, when the `KeycloakOrgEntityProvider` is started and for some reason receives an error back from the Keycloak API, a logline is generated containing the Bearer Token.

**Describe the solution you'd like**
The Brearer Token should be redacted from the log.

**Additional context**
```JSON
{"class":"KeycloakOrgEntityProvider","level":"info","message":"Reading Keycloak users and groups","plugin":"catalog","service":"backstage","taskId":"KeycloakOrgEntityProvider:default:refresh","taskInstanceId":"8309eee5-5658-48a6-9cd7-32305013af2b","type":"plugin"}
```
```JSON
{"config":{"headers":{"Accept":"application/json, text/plain, */*","Authorization":"bearer COMPROMISED-TOKEN","User-Agent":"axios/0.26.1"},"maxBodyLength":-1,"maxContentLength":-1,"method":"get","params":{"first":13200,"max":100},"timeout":0,"transformRequest":[null],"transformResponse":[null],"transitional":{"clarifyTimeoutError":false,"forcedJSONParsing":true,"silentJSONParsing":true},"url":"KEYCLOAK_URL/admin/realms/master/users","xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN"},"message":"Request failed with status code 500","stack":"Error: Request failed with status code 500\n    at createError (/app/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/app/node_modules/axios/lib/core/settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (/app/node_modules/axios/lib/adapters/http.js:322:11)\n    at IncomingMessage.emit (node:events:526:35)\n    at endReadableNT (node:internal/streams/readable:1359:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","status":500}
```

**Comment by vargaadam** [comment]
Any thoughts on that?

**Comment by kadel** [comment]
@tumido, @sabre1041 can you look into this?

**Comment by schultzp2020** [comment]
I'm pretty sure the improper error logging comes from this [line](https://github.com/janus-idp/backstage-plugins/blob/main/plugins/keycloak-backend/src/providers/KeycloakOrgEntityProvider.ts#L251).

**Comment by jerolimov** [comment]
That's true @schultzp2020. Sorry for the delay, let me open a pr until tomorrow. I have the change prepared but was sick. But i feel good enough to do it this evening. :-/

**Comment by schultzp2020** [comment]
@jerolimov What properties are you keeping when you log? On slack we thought the only important properties were `message`, `status` and `stack`. `config` looks like more like a security risk.
