### ISSUE TITLE
Unable to Fetch Tekton Pipeline and TaskRuns if they are present in a different namespace

### ISSUE THREAD

**Issue by srisek** [janus-idp/backstage-plugins#643]
Backstage Plugin: pipelines with Tekton 

The current annotation only picks up tekton pipielineruns and taskruns , where the actual app related k8's resources are deployed. In our case we have the tekton related components (pipelines / pipelines runs and task runs) running in a different namespace that is in specific for the CI purpose.   

Currently by setting the below annotations as per the documentation,

backstage.io/kubernetes-id: test
backstage.io/kubernetes-namespace: test

We have the pipeline runs in the namespace "tekton-app-test"

Due to this we are not getting any pipelineruns or task runs picked up by the plugin and displays no pipeline runs found error.

We have tekton pipelines plugin (@jquad-group/plugin-tekton-pipelines - https://github.com/jquad-group/backstage-jquad#readme) installed which as well allows us to pick the pipeline runs for this use case with the below annotations,
 tektonci/build-namespace: tekton-app-test
 tektonci/pipeline-label-selector: 'build-name=test-app'

Is there a way that this plugin can use a custom annotation that can support this use case.

**Comment by debsmita1** [comment]
@srisek Remove the annotation `backstage.io/kubernetes-namespace: test` from your entity yaml file and the k8s plugin should be able to fetch all the PLRs and other resources associated with your `test` component across all namespaces.

**Comment by invincibleJai** [comment]
closing this based on https://github.com/janus-idp/backstage-plugins/issues/643#issuecomment-1714378644

feel free to re open if it still exists
