### ISSUE TITLE
Upgrade janus plugins like topology and tekon to Patternfly 5

### ISSUE THREAD

**Issue by invincibleJai** [janus-idp/backstage-plugins#648]
Currently, Topology and tekton plugin uses PF 4, this needs to be upgraded to PF 5
 
Topology Plugin: https://github.com/janus-idp/backstage-plugins/blob/main/plugins/topology/package.json#L38-L44
Tekton Plugin: https://github.com/janus-idp/backstage-plugins/blob/main/plugins/tekton/package.json#L37-L41

**Comment by anilabhabaral** [comment]
I would like to take this. Please assign me @invincibleJai

**Comment by invincibleJai** [comment]
Thanks @anilabhabaral for volunteering for it. This ticket would need some collaboration with the PF(Patternfly) team as well and they (PF) have volunteered to help with this so will be nice to get their hands on this as PF 4 to 5 is a major upgrade and there might be some more tickets that can come out as part of this effort so can collaborate on that.

Tagging @jeff-phillips-18 from the PF team.



@anilabhabara would recommend you to look at issues with the label `good-first-issue`  https://github.com/janus-idp/backstage-plugins/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22 This is useful when you are getting started.

**Comment by anilabhabaral** [comment]
Thank you @invincibleJai , I will take a look into the good first issues.
