### ISSUE TITLE
Ansible plugin should list workflow templates

### ISSUE THREAD

**Issue by cooktheryan** [janus-idp/backstage-plugins#652]
**Is your feature request related to a problem? Please describe.**
Currently with the PR for the Ansible plugin we show Ansible Job templates. We should extend this functionality to include showing workflow templates. The api for that is /api/v2/workflow_job_templates/

**Describe the solution you'd like**
We should include the visualization to view workflow templates using a specific labeling of workflow template vs job templates which would have the job template label

**Describe alternatives you've considered**
N/A

**Additional context**
@invincibleJai and #522

**Comment by invincibleJai** [comment]
Thanks @cooktheryan for creating the ticket, currently we show type as `job_template` , for worfklow template should we list these as type `workflow_template`?  and did you mean this when you say `We should include the visualization to view workflow templates using a specific labeling of workflow template vs job templates which would have the job template label`

FYI job_template type:

<img width="1568" alt="image" src="https://github.com/janus-idp/backstage-plugins/assets/5129024/d5728330-e13e-479e-8b25-b62d8a3b002a">

cc @Kasturi1820

**Comment by cooktheryan** [comment]
I agree with you we should show the label type of job_template vs workflow_template where applicable. You were correct with what I was trying to say with the visualization

**Comment by invincibleJai** [comment]
Here is PR for it https://github.com/janus-idp/backstage-plugins/pull/674
