### ISSUE TITLE
Topology plugin devspace code decorator does not appear if CheCluster doesn't have matching labels for catalog entity

### ISSUE THREAD

**Issue by Zaperex** [janus-idp/backstage-plugins#681]
## Describe the bug
Currently, it appears that the `CheCluster` for the dev spaces MUST be located in the `openshift-devspaces` namespace/project 
In addition to that requirement, it appears that the `CheCluster` must also have the specific `backstage.io/kubernetes-id` label for the catalog entity or a label matching the label for the `backstage.io/kubernetes-label-selector` annotation of the catalog entity. If either of these requirements are not met, the code decorator will default back to a git repository instead of the dev space.

Do note that we also cannot create multiple `CheCluster`s on the same cluster (even if you try to install on a different namespace)
![image](https://github.com/janus-idp/backstage-plugins/assets/50030060/5cdaefbb-ad7c-4d19-94fb-9fb2d2851380)

As a result, it appears there's a limitation where the Topology plugin cannot have multiple catalog entities have the devspace code editor when multiple catalog entities (at least 2) use resources from the same cluster, but have different `backstage.io/kubernetes-id` annotations.

Let's suppose we have multiple catalog entities, each with different `backstage.io/kubernetes-id` labels:
Component 1
```yaml title=catalog-info.yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    backstage.io/kubernetes-id: developer-hub
```
Component 2
```yaml title=catalog-info.yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    backstage.io/kubernetes-id: janus-idp
```
Then let's suppose we put the `backstage.io/kubernetes-id: developer-hub` label on the `CheCluster`. As a result, Component 2 will not be able to access this dev space since it doesn't have the matching label. We cannot set `backstage.io/kubernetes-id: janus-idp` onto the `CheCluster` afterwards as it'll overwrite the `backstage.io/kubernetes-id: developer-hub` label.

[Screencast from 2023-08-25 16-08-11.webm](https://github.com/janus-idp/backstage-plugins/assets/50030060/1d8a2561-7ffa-4932-93be-c3b433295cbd)

A workaround is to have the components use the `backstage.io/kubernetes-label-selector` annotation, pointing to unique labels to differentiate between the components, and apply all those unique labels on the CheCluster. Note: the `backstage.io/kubernetes-label-selector` annotation WILL override whatever you set for the `backstage.io/kubernetes-id` annotation. 

## To Reproduce

1. Setup the kubernetes plugin for one cluster
2. Setup two catalog entity components with different `backstage.io/kubernetes-id: <LABEL>` annotations (refer to above examples)
3. Populate cluster with resource (ex: deployment) with the corresponding `backstage.io/kubernetes-id: <LABEL>` labels (at least one for each entity)
4. Apply the `app.openshift.io/vcs-uri: https://github.com/janus-idp/backstage-showcase` annotation to the resources.
5. Install the Red Hat Openshift DevSpaces Operator onto the cluster and create a CheCluster on the `openshift-devspaces` namespace (You may need to create this namespace using the CLI with `oc create namespace openshift-devspaces`.)
Refer to the dev space [documentation](https://access.redhat.com/documentation/en-us/red_hat_openshift_dev_spaces/3.7/html/administration_guide/installing-devspaces#installing-devspaces-on-openshift-using-the-web-console) for how to install it.
6. Apply the  `backstage.io/kubernetes-id: <LABEL>` for one of the catalog entities (ex: `backstage.io/kubernetes-id: developer-hub`)
7. Observe that the devspace code decorator appears for one of the catalog entity (component 1 if you used `developer-hub` as the label)
8. Observe that only the github code decorator appears for component 2

## Expected behavior
We expect the CheCluster to be accessible by all catalog entities regardless of what label is on the CheCluster (shouldn't be restricted to specific catalog entities, especially when the `backstage.io/kubernetes-id` annotation is what most people would use).

**Comment by Zaperex** [comment]
If we don't want to fix, I guess we can just document the workaround of using the `backstage.io/kubernetes-label-selector` for people who want to have multiple entities use the CheCluster resource?

**Comment by tumido** [comment]
cc @invincibleJai

**Comment by invincibleJai** [comment]
@Zaperex Thanks Frank for reporting it. @divyanshiGupta PTAL when you get time.

**Comment by divyanshiGupta** [comment]
@Zaperex thanks for suggestions. For now we can update the documentation clearly mentioning that if the user needs to visualise the Devspaces decorator on multiple entities linked to the same cluster then they need to add `backstage.io/kubernetes-label-selector` to their component config and apply those labels on the CheCluster. Currently there is no other way of fetching the resources as we are using k8s plugin backend and it requires the resources to have either the id label or the selector labels.

**Comment by debsmita1** [comment]
I could think of two ways to address this issue:

1. Users will have to come up with unique labels to differentiate between the components, and the labels have to be added to the associated resources and all the unique labels have to be added to the checluster

  Ex:
  Config-info.yaml of Component-X
  ```
  annotation:
	  backstage.io/kubernetes-label-selector: 'backstage-component=my-backstage-X'
  ```
  Config-info.yaml of Component-Y
  ```
  annotation:
	  backstage.io/kubernetes-label-selector: 'component=my-backstage-Y'
  ```
  Resource associated with component-X
  ```
  labels:
     backstage-component=my-backstage-X
  ```
  Resource associated with component-Y
  ```
  labels:
     component=my-backstage-Y
  ```
  Che cluster
  ```
  labels:
    backstage-component=my-backstage-X
    component=my-backstage-Y
  ```
Or


2. Pass custom label selector query that would fetch resources with `component=<BACKSTAGE_ENTITY_NAME>` or `component=che`
  
  Ex:
  Config-info.yaml of Component-X
  ```
  annotation:
     backstage.io/kubernetes-label-selector: 'component in (my-backstage-X,che)'
  ```
  Config-info.yaml of Component-Y
  ```
  annotation:
     backstage.io/kubernetes-label-selector: 'component in (my-backstage-Y,che)'
  ```
  
  Resource associated with component-X
  ```
  labels:
    component=my-backstage-X
  ```
  Resource associated with component-Y
  ```
  labels:
    component=my-backstage-Y
  ```
  Che cluster
  ```
  labels:
     component=che
  ```
