### ISSUE TITLE
Spike: Explore PatternFly usage with Backstage

### ISSUE THREAD

**Issue by gorkem** [janus-idp/backstage-plugins#70]
**Goal**
Study how PatternFly and existing PatternFly components can be used with Backstage. Find capabilities, limitations and document them. 

**What problem does this solve? Please describe.**
Existing OpenShift console components such as the topology and pipelines views rely heavily on PatternFly. Backstage on the other hand uses Material UI. To evaluate whether we can reuse existing code, we need to determine if it's possible to use PatternFly in a plugin.

**Use cases**
As a plugin developer, I want to use PatternFly components in a Backstage plugin so that I can reuse existing code from OpenShift console.

**Acceptance criteria**
Explore answers the following questions:

- [x] Can I use `@patternfly/react-core` components in a Backstage plugin?
- [x] Can PatternFly CSS be contributed from a plugin, or does it have to be added to the root Backstage app?
- [x] Does PatternFly CSS break the display of Material UI / Backstage components or layout?
- [x] Does Material CSS break display of PatternFly components?
- [x] Do the styles clash? Can we theme either PatternFly or Backstage to mitigate the different look and feel?
- [x] Can I use the `@patternfly/react-topology`?
- [x] Can I use the `@patternfly/react-table`?
- [x] Can I use the `@patternfly/react-charts`?
- [x] How do we handle dark mode?

Document the findings.

**Additional context**

Designing for Backstage: https://backstage.io/docs/dls/design
Backstage plugins: https://backstage.io/docs/plugins/
Customizing Backstage look and feel: https://backstage.io/docs/getting-started/app-custom-theme
PatternFly React docs: https://patternfly-react-main.surge.sh/

**Comment by gorkem** [comment]
@spadgett Can you possibly update this one with an Acceptance criteria and  other information?

**Comment by spadgett** [comment]
@gorkem Happy to, although it looks like I don't have permission to edit issues

**Comment by serenamarie125** [comment]
@spadgett note we have a [separate issue for Topology](https://github.com/janus-idp/backstage-plugins/issues/72)

**Comment by spadgett** [comment]
How PatternFly components look when used in Backstage:

![Screenshot 2023-01-24 at 9 00 55 AM](https://user-images.githubusercontent.com/1167259/214314517-6b8f7693-4ef0-4290-98a3-53e919bce1a3.png)

**Comment by invincibleJai** [comment]
@spadgett does PF component update here based on the dark/light theme? or this is something that needs to be handled/looked into separately

**Comment by spadgett** [comment]
@invincibleJai Let me add it to the list... IIRC this requires manually adding a `pf-theme-dark` class to the root element for PF to update. Presumably we can key off of the Backstage setting and add the class.

**Comment by rtaniwa** [comment]
Moving this one as a task under the Topology epic, and closing as this work is complete.

**Comment by serenamarie125** [comment]
Adding link to Sam's doc [here](https://docs.google.com/document/d/1WZ7h0dXJwr_VZrdRVHa2jj1c6L3_rhOvVicHngMBmok/edit#heading=h.74m5mdrg3qrp)
