### ISSUE TITLE
Study Backstage telemetry system 

### ISSUE THREAD

**Issue by gorkem** [janus-idp/backstage-plugins#71]
**Goal**
Study how backstage [plugin analytics](https://backstage.io/docs/plugins/analytics) work. Discuss how it can be integrated with Red Hat telemetry collection.  

Study how to enable telemetry in general on an instance of Backstage.

**Acceptance criteria**
- The knowledge of plugging analytics mechanics present at the team. 
- Create a document that explains how Red Hat telemetry can be enabled for a plugin. 
- Create a document that explains how telemetry collection be enabled in a Backstage instance.

**Comment by christophe-f** [comment]
Video from BackstageCon 2022: [https://youtu.be/DtGV2zR2z6Y](https://youtu.be/DtGV2zR2z6Y)

**Comment by rtaniwa** [comment]
They also did a [blog post](https://backstage.io/blog/2022/09/08/fyi-plugin-analytics-api) with some additional details that might be helpful.

**Comment by cooktheryan** [comment]
@sallyom could be super helpful here

**Comment by invincibleJai** [comment]
We do have a plugin https://github.com/janus-idp/backstage-plugins/tree/main/plugins/analytics-provider-segment now, is this ticket still valid? 

@kadel / @tumido

**Comment by tumido** [comment]
It is still valid. We do not document or provide a way to hook into RH telemetry.

We discussed a related topic and segued into this yesterday actually:

https://redhat.enterprise.slack.com/archives/C04CUSD4JSG/p1700249071832159?thread_ts=1700249071.832159&cid=C04CUSD4JSG

**Comment by kadel** [comment]
Yes, we will revisit this for the next milestone.

**Comment by tumido** [comment]
FTR for 1.0 we decided to remove the Segment plugin from the instance.

**Comment by christophe-f** [comment]
Everything was done from this epic expect the documentation part that is planned next week.

**Comment by tumido** [comment]
FRT based on @christophe-f 's input this plugin is being added again as a dynamic plugin https://github.com/janus-idp/backstage-showcase/pull/812
