### ISSUE TITLE
Nexus plugin is slow to load docker artifacts

### ISSUE THREAD

**Issue by rmartine-ias** [janus-idp/backstage-plugins#711]
**Describe the bug**
When loading the "Build Artifacts" tab for the first time (in each browser), with a `nexus-repository-manager/docker.image-name:` annotation, the tab takes around 20 seconds to load. This is because of the requests for the docker manifests, which take 6-7 seconds each, on our Nexus. This is past the point where people will click away because it is too slow.

**To Reproduce**

1. Initialize plugin 
2. Add a `nexus-repository-manager/docker.image-name:` annotation to a catalog item
3. Click on the "Build Artifacts" tab (may need to open devtools and disable cache)
4. See time to load

**Expected behavior**

Loading to be near-instant. If possible, load times to be shared among users, rather than repeated per user. Thoughts on how to do this:
* Add a backend to the plugin, with either a request-level or data-level cache. Refresh this on some schedule
* Add config to only fetch the latest N artifacts of each type
* Find a way to not request the full manifests, or at least not block on it -- we should be able to display a list of tags without waiting for the requests to complete. I think only artifact size requires the manifest?
* Suggest adding Varnish or similar in-between backstage and nexus (we'd rather not do this, if possible)
* Two or more of the above

**Screenshots**
<img width="1405" alt="Screenshot 2023-09-05 at 12 49 03 PM" src="https://github.com/janus-idp/backstage-plugins/assets/107639398/9142d230-45a5-40b5-bea3-1a3414b2cd7d">

**Additional context**

My company was planning on creating our own Nexus plugin, but delayed long enough that y'all shipped an OSS one. Since we've budgeted time for this already, we'd like to spend it working to contribute back to the work you're doing. I'm reporting this issue to see if there's something you already have planned for this/start a discussion, so we don't duplicate work you're already doing, or go down a different route than you envisioned.

**Comment by tumido** [comment]
Hey @rmartine-ias,

Thank you for filing an issue here! 🙂 

If you have more ideas or if you would like to steer this plugin in a specific direction or design, please share it! We welcome it, we are open to any suggestions. 🙂 

If you'd like, you can also join us on [Slack](https://join.slack.com/t/janus-idp/shared_invite/zt-1pxtehxom-fCFtF9rRe3vFqUiFFeAkmg) and for our [bi-weekly community calls](https://calendar.google.com/calendar/u/0?cid=amFudXMuaWRwLmNvbW11bml0eUBnbWFpbC5jb20).


Back to the issue:
What if we paginate on the [`searchServiceFetcher`](https://github.com/janus-idp/backstage-plugins/blob/9463a9d3b4fd6eef8e415afd32049096fc25ec9a/plugins/nexus-repository-manager/src/api/nexus-repository-manager-api-client/nexus-repository-manager-api-client.ts#L123C30-L123C50) (we can use the `continuationToken` for pagination)? We can use this to lazy load additional entries and populate the rows on the fly. I don't think this would be too complex to implement and it would certainly be better than limiting the list of displayed entries. WDYT?

**Comment by rmartine-ias** [comment]
Hello @tumido and @schultzp2020! We definitely have some thoughts that we'll want to share -- I'll make a post in the slack, and add GH issues for discoverability as well. Will not be able to make it to the meetings (at least regularly), unfortunately; they're three hours before I'm typically awake.

Partially good news -- I figured out why our nexus was being slow. Requesting a manifest [without certain accept headers](https://docs.docker.com/registry/spec/manifest-v2-2/#backward-compatibility) makes it think only manifest schema 1 is supported, and on-the-fly rewriting to schema 1 is slow. (That's where I stopped looking. But I do wonder why it's slow, and why nexus doesn't cache those files.) I have a code change in the works for the nexus plugin to send those headers when requesting docker manifests. That significantly speeds up requests, but for resources with hundreds of images, it still takes a long time, so I don't want to close this issue. 

I like the idea of paginating, but I think it can be one step faster, maybe. I don't know exactly the right words for things, but this is what I'm picturing: each page of search dumps the manifest download URLs into a queue. That queue is fetched from in groups of \<pagination amount> (see image) (at least for the first request), and so we can draw the table as soon as the first \<pagination amount> have returned, and keep fetching in the background. This would be faster than waiting for the data from a full page of search.

<img width="1320" alt="Screenshot 2023-09-07 at 1 31 10 PM" src="https://github.com/janus-idp/backstage-plugins/assets/107639398/6ea8a9c9-ba95-4ac7-ae51-1b358cb0c750">

This could even be snappier by displaying the data from the search results immediately (version, repo, name, sha, modified) and async loading the size field as above.

A few other thoughts:

* I think default sort should be date modified, descending (which needs a little bug fix, clicking the table's modified field seems to sort alphabetical by human-readable date -- will open an issue). This needs a `sort=version` parameter added to the nexus search API call. This would make the "first five results" much more likely to be meaningful. I can make this change if you all agree.
    <img width="190" alt="Screenshot 2023-09-07 at 1 09 54 PM" src="https://github.com/janus-idp/backstage-plugins/assets/107639398/02abe736-7009-4673-a2bb-913cf4494e3e">
* Something we're looking to add is the ability to have multiple artifact types per Component (maybe an OpenAPI spec, two maven artifacts, and a docker image). It would be ideal to handle this so that on first paint, the latest of all types are interleaved, limited to \<pagination amount> in total. (Or maybe it would be better to add them to the table as they come?) This might be a "cross the bridge when we come to it" type thing, but I wanted to bring it up in case it would influence the design.
* If we want to be able to let users sort/filter the table, lazy loading the rest of the results on page navigation introduces a lot of latency at that point. If everything is fetched in the background though, that's potentially a lot of unneeded API calls if the user never navigates past the first page, sorts, or filters. I'd lean towards the second, I think, for a better user experience.


@tplass-ias, anything I'm missing?

**Comment by tplass-ias** [comment]
From what I've heard from our users, they are mostly interested in quickly checking that their latest version has arrived in nexus, so limiting how many entries are displayed is actually preferred imo

For browsing through the full list of versions of an artifact, I think that's what the Nexus UI itself is for, and ideally the Backstage UI would have a convenient link to click for that, e.g. `${NEXUS_URL}/#browse/search/docker=attributes.docker.imageName%3D${IMAGE_NAME}` for docker images

**Comment by rmartine-ias** [comment]
For the quickly checking the latest version, I was thinking the main way they'd do that would be a home-tab card with the latest asset of each type. Saves a click over going to the dedicated tab.

Not to derail, but I'm still sort of unclear on the more general philosophical point of what Backstage plugins should do, and what they should delegate to the underlying tool via click-through. Do you have a heuristic you're using?
