### ISSUE TITLE
Spike: Explore PatternFly Topology usage with Backstage

### ISSUE THREAD

**Issue by serenamarie125** [janus-idp/backstage-plugins#72]
**Goal**
Study how the PatternFly Topology component can be used with Backstage. Find capabilities, limitations and document them.

**What problem does this solve? Please describe.**
Our OpenShift Application Topology component is highly desirable by OpenShift Users.  We'd like to bring this in as a UI plugin.  To evaluate whether we can reuse existing code, we need to first determine if it's possible to use PatternFly Topology in a plugin.

**Use cases**
As a plugin developer, I want to use PatternFly Topology in a Backstage plugin so that I can reuse existing code from OpenShift console.

Acceptance criteria
Explore answers the following questions:

- [x] Can I use @patternfly/react-topology components in a Backstage plugin?

- [x] Does Material CSS break display of Topology components?

- [x]  Do the styles clash? Can we theme either PatternFly or Backstage to mitigate the different look and feel?

- [x] Can I use the @patternfly/react-topology?

- [x] Document the findings.

** Additional context **

Designing for Backstage: https://backstage.io/docs/dls/design
Backstage plugins: https://backstage.io/docs/plugins/
Customizing Backstage look and feel: https://backstage.io/docs/getting-started/app-custom-theme
PatternFly React docs: https://patternfly-react-main.surge.sh/

**Comment by invincibleJai** [comment]
The findings has been captured here https://docs.google.com/document/d/1AgvotEMzol4ra12Vr_dPuGO1GsrAN9I9mU27w7MyMdk/edit

**Comment by serenamarie125** [comment]
@invincibleJai do you mind if I label this as a kind/story and make it part of the Topology epic?

**Comment by rtaniwa** [comment]
All the tasks on this one have been completed. I will close this out but please reopen if there is still uncaptured work that needs to be done. Thanks.
