### ISSUE TITLE
Not able to get users in backstage by using janus Keycloak backend plugin for Backstage. getting 401

### ISSUE THREAD

**Issue by kulkarnijanhavi** [janus-idp/backstage-plugins#736]
Description :
I am using janus  [Keycloak backend plugin for Backstage](https://janus-idp.io/plugins/keycloak/) for getting users from keycloak and showcase them backstage app. But I am getting following error in backstage console.

error Request failed with status code 401

I am using this command to start keycloak on port 8080.

podman run -p 8080:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin quay.io/keycloak/keycloak:22.0.3 start-dev

Getting following error for keycloak

type=CLIENT_LOGIN_ERROR, realmId=ca698df5-850a-4f62-a17d-1c054243d6b9, clientId=myclient, userId=null, ipAddress=10.0.2.100, error=client_not_found, grant_type=client_credentials

I have cross checked the client credentials and those are correct. 

1. Create backstage app : https://backstage.io/docs/getting-started/
2. Setup keycloak : https://www.keycloak.org/getting-started/getting-started-podman
3. Create new realm, client under new realm and users
4. For client make sure Client authentication is enabled and Service accounts roles is enabled
5. add following realm-management client roles to client: 

query-groups
query-users
manage-users

6. Install keycloak plugin for backstage by janus and follow all the steps : https://janus-idp.io/plugins/keycloak/
7. update app-config.yaml with keycloak credentials (realm, clientId and client secret)
8. run backstage app by using yarn dev

Expected behavior:
I should be able to see all the users in backstage app (Catalog->User)

Screenshots :
![image](https://github.com/janus-idp/backstage-plugins/assets/145097259/e714f102-20c0-4272-899f-240d30d575ec)

![image](https://github.com/janus-idp/backstage-plugins/assets/145097259/115e9b5e-b0ea-4b63-95bd-bf1f8e546373)

**Comment by hmargarido** [comment]
Same issue here

**Comment by Zaperex** [comment]
@hmargarido what are you configurations like?

**Comment by RaulGrosmam** [comment]
Hi, same problem here.

Here's my configs:

app-config.yaml:

catalog:
  rules:
    - allow: [Component, Group, User, Template, System, API, Resource]

  providers:
    keycloakOrg:
      default:
        baseUrl: https://mykeycloak/auth
        loginRealm: myrealm
        realm: myrealm
        clientId: backstage
        clientSecret: mysecret

I'm using the Legacy configuration configuration.

**Comment by Zaperex** [comment]
@RaulGrosmam Can I ask what version of keycloak you are using? [The `/auth` context shouldn't be required if you're using keycloak 17 or higher](https://github.com/keycloak/keycloak/issues/10464). Can you try removing the `/auth` for your `baseUrl` configuration?

**Comment by RaulGrosmam** [comment]
Our Keycloak version is below 17.
But for testing, I've tried to remove /auth, the error still the same :(

**Comment by Zaperex** [comment]
Hi @RaulGrosmam , I tested with a local instance of Keycloak 16.1.1 and it worked fine for me:
```bash
docker run -p 8080:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin quay.io/keycloak/keycloak:16.1.1
```
and the following configurations:
```yaml
catalog:
  providers:
    keycloak:
      default:
        baseUrl: http://localhost:8080/auth
        realm: backstage
        loginRealm: backstage
        clientId: backstage
        clientSecret: Xj8H5ahnsCrbxsMru1bjPVKQK0LsKMSd
```
I setup a test realm called `backstage` and generated a client with clientId `backstage`, set it's `access-type` to `confidential` and enabled service accounts:
![image](https://github.com/janus-idp/backstage-plugins/assets/50030060/d2f6f3ed-614f-452b-86d9-fe3413fb48de)

Then I added the following `realm-management` roles for the service account:
![image](https://github.com/janus-idp/backstage-plugins/assets/50030060/1d2d2d25-f435-4e46-a1f4-1a6b5fd09cbe)

Then grabbed the client secret from the credentials tab to use for the backstage configurations
![image](https://github.com/janus-idp/backstage-plugins/assets/50030060/19915aa8-f533-4528-adc4-a2a5418bc0bf)

Can I ask if your configurations differed at all from my configurations?

**Comment by RaulGrosmam** [comment]
I didn't have a Service Account Enable.
Now it's working. Many thanks!
