### ISSUE TITLE
🔌 Plugin: Ingest users and groups from OCP

### ISSUE THREAD

**Issue by serenamarie125** [janus-idp/backstage-plugins#78]
### 🔖 Summary

Create a new plugin to ingest users and groups from OCP

### ✌️ Context

@sabre1041 is looking into this

### 👀 Have you spent some time to check if this plugin request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by jasperchui** [comment]
Closed as implemented by keycloak.
