### ISSUE TITLE
[Tekton plugin]: Update user experience for tekton plugin

### ISSUE THREAD

**Issue by invincibleJai** [janus-idp/backstage-plugins#804]
**Description**
As a user, I want to visualize the list of all pipelineRuns and task run status at a glance in the CI tab

<img width="1161" alt="image" src="https://github.com/janus-idp/backstage-plugins/assets/5129024/5654cfc1-e62d-4537-939f-a122caea3265">

**Acceptance Criteria**

- [x] Have appropriate filter tools for Cluster, status
- [x] Have search for table
- [x] On click of each row, it should expand and show the PLR visualization
- [x] On click on status it should show PLR logs modal as it does today
- [x] Table should have pagination
- [x] expand and collapse icon on the header to expand/collapse all visible rows at once

**Comment by invincibleJai** [comment]
@ShiranHi / @divyanshiGupta / @debsmita1 PTAL and feel free to add/modify if anything is not accurate

**Comment by ShiranHi** [comment]
Prototype: 
https://www.figma.com/proto/Gp6QQ0wtRO3RSCphRZIdjQ/RHDH-Theme-for-Backstage?type=design&node-id=295-127&t=wxAQOpamCxu8Ad6V-1&scaling=min-zoom&page-id=162%3A592&starting-point-node-id=230%3A474&mode=design

Figma file: 
https://www.figma.com/file/Gp6QQ0wtRO3RSCphRZIdjQ/RHDH-Theme-for-Backstage?type=design&node-id=295%3A127&mode=design&t=NkIYl4IXIw4c7Usa-1
