### ISSUE TITLE
Plugin Entity Provider schedules should be configurable through the app configurations even with schedule already defined in code

### ISSUE THREAD

**Issue by Zaperex** [janus-idp/backstage-plugins#816]
### What do you want to improve?
The plugins using an Entity Provider should have the Entity Provider schedule provided from the `app-config.yaml` take precedence over the hardcoded schedule in the code.
The current plugins using an entity provider in our repository are:
- [3scale-backend](https://github.com/janus-idp/backstage-plugins/blob/94a81885b3893c287772d4b4c53aca37f1096c0b/plugins/3scale-backend/src/providers/ThreeScaleApiEntityProvider.ts#L61-L72)
- [ocm-backend](https://github.com/janus-idp/backstage-plugins/blob/94a81885b3893c287772d4b4c53aca37f1096c0b/plugins/ocm-backend/src/providers/ManagedClusterProvider.ts#L85-L87)
- [aap-backend](https://github.com/janus-idp/backstage-plugins/blob/94a81885b3893c287772d4b4c53aca37f1096c0b/plugins/aap-backend/src/providers/AapResourceEntityProvider.ts#L46-L52)
- [keycloak-backend](https://github.com/janus-idp/backstage-plugins/blob/94a81885b3893c287772d4b4c53aca37f1096c0b/plugins/keycloak-backend/src/providers/KeycloakOrgEntityProvider.ts#L135-L137)

Additionally, a method to manually trigger the entity providers outside their scheduled times should exist.

### What is the current behavior?
Currently all of the above plugins' entity provider schedules can't be configured from the `app-config.yaml`'s `catalog.providers.<plugin>.schedule` field.
### What will the new behavior be?
Schedules from the `app-config.yaml` should override the schedules hardcoded into the backstage instance when installing the entity providers.

Additionally, a method to manually trigger the entity providers outside their scheduled times should exist.

**Comment by davidfestal** [comment]
Generally we have to use scheduler configuration from the `app-config` when we switch to dynamic plugins.

**Comment by Zaperex** [comment]
After investigating this further, I realized to be able to read from the `app-config.yaml`, the backstage instance needs to have the entity providers installed with the `scheduler: env.scheduler` set in the options. 

Currently, it's possible to have both the `scheduler` and the `schedule` set, but the `schedule` will take precedence. 
```yaml
schedule: env.scheduler.createScheduledTaskRunner({
  frequency: { hours: 1 },
  timeout: { minutes: 50 },
  initialDelay: { seconds: 15 },
}),
scheduler: env.scheduler,
```

The goal of this issue is to make the `scheduler` take precedence since once the backstage instance has been built into an image, the end user can only make changes to the schedule in the `app-config.yaml` and will no longer have the ability to change the `schedule` option in the code without rebuilding a new image.
