### ISSUE TITLE
🔌 Plugin: Pipelines as code

### ISSUE THREAD

**Issue by serenamarie125** [janus-idp/backstage-plugins#82]
**Goal**
Provide a plugin to enable users to see that a git repo is configured for PAC, and is able to view the PLR, associated Task Runs and logs.

**What problem does this solve? Please describe.**
-- tbd -- 

**Use cases**
As a backstage user, I want easy access to the the status of the PLR execution when triggered by a `Pull` Request or a `Push`

**Acceptance criteria**
-- tbd -- 

**Additional context**
[Pipelines as Code](https://pipelinesascode.com/)

**Comment by tumido** [comment]
Should this be considered as an extension to the #57?

**Comment by serenamarie125** [comment]
@tumido I think that's something we should evaluate!
