### ISSUE TITLE
Spike on Tekton plugin

### ISSUE THREAD

**Issue by serenamarie125** [janus-idp/backstage-plugins#83]
## Goal
Evaluate the[ upstream Tekton plugin](https://github.com/jquad-group/backstage-jquad#readme), using this [BS Plugin Evaluation Templates](https://docs.google.com/document/d/10bltPXv9G-2Ev_JmtZyk0H5FJeptZCmYhS6M95CLcHU/edit)

**Comment by serenamarie125** [comment]
@lokeshrangineni can you add the GDoc including details of the spike?  Once we have that available, we can schedule the review and talk about next steps.  Thanks!

**Comment by lokeshrangineni** [comment]
@serenamarie125  I am currently working on preparing the google doc with all the details. I am expecting it to finish by Monday (02/13/2023) EOD. I will let you know the progress.

**Comment by rtaniwa** [comment]
Including link to the [evaluation doc](https://docs.google.com/document/d/1rVDWGcy1dBsNvT6ur_1c_5p52pfZZtVT-6GE0b99F6E/edit?usp=sharing).
