### ISSUE TITLE
Topology Plugin: Default Runtime icon

### ISSUE THREAD

**Issue by debsmita1** [janus-idp/backstage-plugins#835]
### What do you want to improve?

Currently, the Topology Plugin does not display a default runtime icon on workload nodes when the runtime name does not correspond to any of the predefined runtime names listed in this Readme: https://github.com/janus-idp/backstage-plugins/tree/main/plugins/topology. This ticket has been raised to resolve this problem.

### What is the current behavior?

The workload node shows blank if the runtime name does not match any of the predefined runtime names.

<img width="831" alt="Screenshot 2023-10-16 at 7 14 39 PM" src="https://github.com/janus-idp/backstage-plugins/assets/22490998/d6cd8919-44a7-4393-be6c-636c38a34fba">

### What will the new behavior be?

It should show a default runtime icon.

Related to : https://github.com/janus-idp/backstage-plugins/issues/547

**Comment by debsmita1** [comment]
cc @divyanshiGupta

**Comment by parvathyvr** [comment]
Hi @debsmita1 @divyanshiGupta How about one among these options from the Material symbols?👇
1. [Hub](https://fonts.google.com/icons?selected=Material+Symbols+Outlined:hub:FILL@0;wght@400;GRAD@0;opsz@48)
2. [App Badging](https://fonts.google.com/icons?selected=Material+Symbols+Outlined:app_badging:FILL@0;wght@400;GRAD@0;opsz@48)
3. [Linked services](https://fonts.google.com/icons?selected=Material+Symbols+Outlined:linked_services:FILL@0;wght@400;GRAD@0;opsz@48)
CC @ShiranHi @yuvalgalanti
