### ISSUE TITLE
Role implemenation for RBAC

### ISSUE THREAD

**Issue by gorkem** [janus-idp/backstage-plugins#836]
### What do you want to improve?
RBAC plugin should be able to create roles and assign groups and users to these roles. 

### What is the current behavior?
RBAC plugin authorizes only via groups and users. 

### What will the new behavior be?
RBAC plugin uses Roles to authorize users and groups.

Roles can be created and stored on the Backstage database by the RBAC Admins. They can include Groups and Users but not other roles.  The groups that are included in the roles may consist of other groups. Roles are a new entity type but they are not stored as part of the Software Catalog. RBAC plugin stores them and provides REST APIs to modify them. 

The implementation will require the [BackstageRoleManager](https://github.com/janus-idp/backstage-plugins/blob/c3417d7e02a80e65c1ab8ec98ccc961ed0527f08/plugins/rbac-backend/src/service/role-manager.ts#L74) to be modified to determine Role membership as well as group membership.

**Comment by invincibleJai** [comment]
should we link this to Epic https://github.com/janus-idp/backstage-showcase/issues/303

**Comment by AndrienkoAleksandr** [comment]
Is this for GA?

**Comment by invincibleJai** [comment]
> RBAC plugin should be able to create roles and assign groups and users to these roles.

Yeah, I think it is and Role will have groups/users and can even add permissions and associated actions based on what i understood

and we would also need the ability to edit and delete the roles (more details can be seen in this epic https://github.com/janus-idp/backstage-plugins/issues/849)

cc @gorkem

**Comment by gorkem** [comment]
Yes. It is for GA.

**Comment by invincibleJai** [comment]
> Is this for GA?

Yeah, I think it is. 

> RBAC plugin should be able to create roles and assign groups and users to these roles.

We should be able to assign groups and users to these roles along with permissions and associated actions based on what i understood. We also need the ability to perform CRUD on these roles (Associated UI epic https://github.com/janus-idp/backstage-plugins/issues/849)

cc @gorkem
