### ISSUE TITLE
Spike on GitOps plugin

### ISSUE THREAD

**Issue by serenamarie125** [janus-idp/backstage-plugins#84]
## Goal
Evaluate the[ upstream Argo plugin](https://roadie.io/backstage/plugins/argo-cd/?utm_source=backstage.io&utm_medium=marketplace&utm_campaign=argo-cd), using this [BS Plugin Evaluation Templates](https://docs.google.com/document/d/10bltPXv9G-2Ev_JmtZyk0H5FJeptZCmYhS6M95CLcHU/edit)

## Notes
It looks like the Argo upstream plugin is only available on Roadie.  If that's the case, let's get as much information as possible.

**Comment by rtaniwa** [comment]
Details on the upstream plugin:
[Details from upstream contributer](https://roadie.io/backstage/plugins/argo-cd/?utm_source=backstage.io&utm_medium=marketplace&utm_campaign=argo-cd)
[Source repo (both frontend and backend plugins)](https://github.com/RoadieHQ/roadie-backstage-plugins/tree/main/plugins)

**Comment by tumido** [comment]
If it helps the reviewer, the plugin can be seen deployed and in action for example here:

https://service-catalog.operate-first.cloud/catalog/default/component/backstage/ci-cd (above github actions)

You can click on the ArgoCD application name to reveal additional details.

**Comment by rtaniwa** [comment]
I am going to close this one out as the spike is complete. We will review the spike and track follow on issues with https://github.com/janus-idp/backstage-plugins/issues/110.
