### ISSUE TITLE
Adopting openshift-merge-robot flow

### ISSUE THREAD

**Issue by kadel** [janus-idp/backstage-plugins#845]
This repository contains a lot of different plugins maintained by other people or teams.

Adopting `openshift-merge-robot` using `OWNERS` files to designate responsibility over each plugin could improve PR reviews. 

I'm proposing the following system:
- each PR will require at least one `/lgtm` (from the reviewer)  and one `/approve` (from the approver), approvers can do both at once
- The top levels `OWNERS` file will contain a list of approvers for the whole repository. This will include everyone who currently has write access. 
- each plugin in `plugins/` directory should have `OWNERS` file that contains a list of reviewers.

**Comment by tumido** [comment]
Yes please! Let's enable prow here! 🙂

**Comment by invincibleJai** [comment]
Closing it as this is enabled now.
