### ISSUE TITLE
App Topology - Visualize resources of the Deployment kind as readonly

### ISSUE THREAD

**Issue by serenamarie125** [janus-idp/backstage-plugins#85]
@invincibleJai please update this with initial story for https://github.com/janus-idp/backstage-plugins/issues/58

**Description**
As a developer, I want to visualize resources of the Deployment kind with pods ring demonstrating pod status and decorators for the route in a sample plugin for topology as Read-only. The visualization should be the same as in ODC as part of this work mock the data for the required resources and create the required data model.

**Acceptance Criteria**

- [x] Visualize resource of kind deployment and deployment config in Topology, show associated pod rings along with pod status
- [x] Workload resources like Deployments and Pods will be shown in a visual group based on the below label
   ```yaml
   'app.kubernetes.io/part-of': <GROUP_NAME>
   ```
- [x] Workload resources like Deployment or Pod will be shown with a visual connector based on the below annotations
   ```yaml
   'app.openshift.io/connects-to': '[{"apiVersion": <RESOURCE_APIVERSION>,"kind": <RESOURCE_KIND>,"name": <RESOURCE_NAME>}]'
   ```
- [x] Push the code to GitHub and any changes need to be documented as required. (Needs to check on with GitHub repo)

**Additional Details:**

For labels and annotations check https://github.com/redhat-developer/app-labels/blob/master/labels-annotation-for-openshift.adoc

**Comment by invincibleJai** [comment]
Creating stories for https://github.com/janus-idp/backstage-plugins/issues/58 

Feel free to update as needed

cc @serenamarie125 @rtaniwa

**Comment by invincibleJai** [comment]
associated PR https://github.com/janus-idp/backstage-plugins/pull/104
