### ISSUE TITLE
Review of Keycloak plugin

### ISSUE THREAD

**Issue by serenamarie125** [janus-idp/backstage-plugins#86]
## Goal
Review the[ upstream Janus keycloak plugin](https://github.com/janus-idp/backstage-plugins/tree/main/plugins/keycloak-backend).
(do we need a template for this?)

## Why is this needed?
Review features and functionality of this plugin.  

## Acceptance Criteria
- [ ] Identify and add GH stories needed before this epic is considered "complete" for Milestone 01 (tag with appropriate milestone & include in #54 
- [ ] Identify and add GH stories, considered as enhancements which can be accomplished before Milestone 01

**Comment by rtaniwa** [comment]
This was done. We are good with where we are, other than doc review which has a separate issue.
