### ISSUE TITLE
Review of OCM plugins

### ISSUE THREAD

**Issue by serenamarie125** [janus-idp/backstage-plugins#87]
## Goal
Review the upstream OCM plugins (do we need a template for this?):

- [ocm backend](https://github.com/janus-idp/backstage-plugins/tree/main/plugins/ocm-backend)
- [ocm common](https://github.com/janus-idp/backstage-plugins/tree/main/plugins/ocm-common)
- [ocm](https://github.com/janus-idp/backstage-plugins/tree/main/plugins/ocm)

## Why
Review features and functionality of this plugin to identify gaps before milestone as well as add possible backlog items for the future. 

## Acceptance Criteria
- [ ] Identify and add GH stories needed before this epic is considered "complete" for Milestone 01 (tag with appropriate milestone & include in #54 
- [ ] Identify and add GH stories, considered as enhancements which can be accomplished before Milestone 01

**Comment by rtaniwa** [comment]
@serenamarie125 not sure we need this issue? IIRC you did a review of the UI via #107 that you just need to write up the results. If that is the case, can this be closed as a dupe?
