### ISSUE TITLE
docs(tekton): update README

### ISSUE THREAD

**Issue by schultzp2020** [janus-idp/backstage-plugins#873]
### What do you want to improve?

The Tekton README.

### What does the current documentation state?

The README [references](https://github.com/janus-idp/backstage-plugins/blob/main/plugins/tekton/README.md?plain=1#L124-L145) a `<TektonPage />` component that no longer exists. 

### What would you like to be added/updated in the documentation?

The new component that replaces `<TektonPage />`.

**Comment by schultzp2020** [comment]
@divyanshiGupta can you take a look at this? I think the behavior changed in https://github.com/janus-idp/backstage-plugins/pull/839.

**Comment by divyanshiGupta** [comment]
@schultzp2020 thanks for brining this up. I will update the README.
