### ISSUE TITLE
App Topology - Finalize on architecture for Topology-plugin

### ISSUE THREAD

**Issue by invincibleJai** [janus-idp/backstage-plugins#90]
Description
As a developer, I want to get the ability to list/watch data for k8s resources like Deployment, DeploymentConfi, Service, Route per namespace, label selector, etc 

Acceptance Criteria

- [ ]  Finalize the approach needed to have the ability to list/watch data for k8s resources like Deployment, DeploymentConfi, Service, Route per namespace, label selector, etc 
- [ ] Do we need to have a dedicated topology-backend?
- [ ] What does the topology-backend will do?
- [ ] Will [k8s-plugin for backstage](https://github.com/backstage/backstage/tree/master/plugins/kubernetes) be the prerequisite for the topology backend?
- [ ] Can we list/watch resources like Deployment, DeploymentConfi, Service, Route per namespace, label selector, etc?
- [ ] Capture all details in doc

 
Additional Details:

Check on the outcome of spike https://github.com/janus-idp/backstage-plugins/issues/56 

This would need discussion / meeting with Architect / Lead / etc and based on the finalized architecture, we would need to have more stories

**Comment by invincibleJai** [comment]
Creating stories for https://github.com/janus-idp/backstage-plugins/issues/58 

Feel free to update as needed

cc @serenamarie125 @rtaniwa @gorkem @spadgett

**Comment by rtaniwa** [comment]
@invincibleJai  anything left to do on this one, or have all the tasks been addressed in our other stories/tasks?
