### ISSUE TITLE
RBAC: Capture modified information of roles

### ISSUE THREAD

**Issue by PatAKnight** [janus-idp/backstage-plugins#900]
### What do you want to improve?
Add the ability to store when and by who a role was modified.

### What is the current behavior?
We do not store information on who a role is modified by or when a role is modified.

### What will the new behavior be?
Store the information and provide a way to retrieve it.

**Comment by AndrienkoAleksandr** [comment]
I guess it should be subtask for audit logging: https://github.com/janus-idp/backstage-showcase/issues/362
