### ISSUE TITLE
rbac: rbac-backend plugin fails with  ssl database connection

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [janus-idp/backstage-plugins#913]
### Describe the bug

rbac-backend plugin fails with  ssl database connection

### Expected Behavior
rbac-backend plugin should  support ssl database connection.

### What are the steps to reproduce this bug?
Issue was reproduced with showcase gitops installation. Thanks @PatAKnight for but report.

**Comment by kadel** [comment]
Bug has been fixed in the plugin, but we still need to upgrade the plugin in the showcase

**Comment by AndrienkoAleksandr** [comment]
@kadel, thanks. https://github.com/janus-idp/backstage-showcase/pull/761
