### ISSUE TITLE
RBAC: CSV repopulates database whenever there is a server restart

### ISSUE THREAD

**Issue by PatAKnight** [janus-idp/backstage-plugins#924]
### Describe the bug

When there is a restart of the server and the `policies-csv-file` and `database.enabled` fields are set, the CSV policy will repopulate the database with the original permission policies.

### Expected Behavior

This opens up a question on how we should handle cases where there is a CSV file included and the Database enabled.

Should we only allow for one or the other to prevent the potential of the database being repopulated with the CSV file on restart

or 

Should we save back into the CSV file if it is included (Personally, I like this approach as this can be useful whenever a database is not present)

### What are the steps to reproduce this bug?

1. Create an RBAC policy CSV with the permission `p, user:default/<YOUR_USERNAME>, catalog-entity, read, deny`
2. Set `policies-csv-file` and `database.enabled` fields in the `app-config`
3. Start server
4. Update the permission policy to `p, user:default/<YOUR_USERNAME>, catalog-entity, read, allow`
5. Restart server
6. Notice that there are now two permission policies in the database:
  ```CSV
  p, user:default/<YOUR_USERNAME>, catalog-entity, read, allow # Updated permission policy
  p, user:default/<YOUR_USERNAME>, catalog-entity, read, deny # Permission policy from the CSV
  ```

**Comment by kadel** [comment]
There is second option how we can solve this at https://github.com/janus-idp/backstage-plugins/issues/924

**Comment by regicsolutions** [comment]
Agree with the second option and saving it back to the CSV
