### ISSUE TITLE
[TEKTON] Unable to expand the PLR details if it's expanded initially and new PLR run gets added to the list

### ISSUE THREAD

**Issue by invincibleJai** [janus-idp/backstage-plugins#939]
### Describe the bug

Intermittently unable to expand the PLR details if it's expanded initially and a new PLR run gets added to the list. Once i refresh i could do it.

### What are the steps to reproduce this bug?

1. In janus/RHDH tekton plugin is properly installed and configured and under CI tab if there is one PLR call it plr1 and the user expands the PLR to view task runs 
2. Then rerun PLR from OCP
3. checks CI tab for service entity and the expanded PLR i.e plr1 gets closed and shows more PLR
4. user can never expand PLR i.e prl1 again unless page is refreshed

<img width="1501" alt="image" src="https://github.com/janus-idp/backstage-plugins/assets/5129024/eea58881-0f44-46a9-8982-bb29d1141de1">

**Comment by rohitkrai03** [comment]
https://github.com/janus-idp/backstage-plugins/pull/980 also fixed this issue.

**Comment by rohitkrai03** [comment]
@invincibleJai Closing this issue since https://github.com/janus-idp/backstage-plugins/pull/980 fixed this as well.
