### ISSUE TITLE
[Tekton] Could not sort PipelineRuns by duration

### ISSUE THREAD

**Issue by jerolimov** [janus-idp/backstage-plugins#946]
### Describe the bug

PipelineRuns isn't sortable in an understandable order by duration. It looks random to the user.

https://github.com/janus-idp/backstage-plugins/assets/139310/7b1e5e0a-b60a-40c7-b66c-aad3bd698750

After looking into the code, I saw that the column duration sorts the elements by `status.completionTime`.

### Expected Behavior

The sort order should match the shown duration (`status.completionTime - status.startTime`).

### What are the steps to reproduce this bug?

1. Create and run multiple PipelineRuns that allow you to sort them by duration.
2. Open a component that shows this PipelineRuns
3. Click on the duration column and check the order

### Versions of software used and environment

Local backstage-plugins instance with @janus-idp/backstage-plugin-tekton 3.1.5

**Comment by rohitkrai03** [comment]
@jerolimov FYI, we have the same issue in ODC right now. We should also track that as a bug and get this fixed there.
