### ISSUE TITLE
🔌 Plugin: Learning paths plugin

### ISSUE THREAD

**Issue by serenamarie125** [janus-idp/backstage-plugins#97]
## Goal
The goal of this epic is to develop a new Backstage UI plugin in the Janus repo.  This UI plugin will provide the ability for application developers using Backstage to easily access OpenShift learning paths.

### Use cases
- As an application developer, I want easy access to the OpenShift Learning Paths that are available on the Developer Sandbox

**Acceptance criteria**
A clear and concise list of acceptance criteria, noting what will be delivered as part of this epic. This will help identify associated testing, documentation and support needs.

## Notes
Need to investigate a phased approach
Phase 1 - tile with a link to https://developers.redhat.com/learn
Phase 2 - Catalog of learning paths available from within Backstage, so developers are able to see what's available easily without having to exit Backstage.  Clicking on the tile in the catalog will invoke the Learning Path outside of the Backstage portal.

**Comment by serenamarie125** [comment]
@myfear FYI

**Comment by jasperchui** [comment]
Closed as complete.
