### ISSUE TITLE
regex-actions: typo in install docs

### ISSUE THREAD

**Issue by tplass-ias** [janus-idp/backstage-plugins#979]
### Describe the bug

[Docs](https://github.com/janus-idp/backstage-plugins/blob/9b39056f6c66e9a6a0a5d0c4059420dff66db263/plugins/regex-actions/README.md?plain=1#L18) say:
```shell
yarn workspace backend add @janus-idp/backstage-plugin-regex-actions
```

but [package.json](https://github.com/janus-idp/backstage-plugins/blob/60b49ab3e25ec9cad5d5d382fb75e6c64a6e6229/plugins/regex-actions/package.json#L2) sets a different name for the package:
```json
  "name": "@janus-idp/backstage-scaffolder-backend-module-regex",
  ```

### What are the steps to reproduce this bug?

1. run `yarn workspace backend add @janus-idp/backstage-plugin-regex-actions`
2. ---> package is not found

### Versions of software used and environment

noticed while trying to install v1.2.2 of the regex-actions plugin

**Comment by invincibleJai** [comment]
Closing it as this has been fixed with https://github.com/janus-idp/backstage-plugins/pull/1132
