### ISSUE TITLE
[Tekton]: add CVE summary as a column in Pipelinerun list view

### ISSUE THREAD

**Issue by karthikjeeyar** [janus-idp/backstage-plugins#986]
**Description:**

 Display CVE summary as `vulnerabilities` column in Pipelinerun list page. 
 

-  CVE summary should be shown for pipelineruns with scanner tasks
-  Fallback value should be displayed for pipelineruns without scanner tasks
-  Users should be able to sort the table by `Vulnerabilities` column

 
 **Additional notes:**
 
 When user's `PipelineRun` includes any CVE scanner task and if that `PipelineRun` which emits a result that ends with the string **SCAN_OUTPUT**. 
 
 eg: MY_CUSTOM_SCAN_OUTPUT and the value in the following format
```
{"vulnerabilities":{
"critical": 13,
"high": 29,
"medium": 32,
"low": 3,
"unknown": 0},
"unpatched_vulnerabilities": {
"critical": 0,
"high": 1,
"medium": 0,
"low":1}
}
```

**Design:**

![image](https://github.com/janus-idp/backstage-plugins/assets/9964343/b24ff2f4-b4c2-47bd-b135-68a6b927e208)

**Comment by karthikjeeyar** [comment]
@invincibleJai I am not able to assign GH issues to myself to anyone, could you please help?

**Comment by cmoulliard** [comment]
Can we see the detail about the vulnerabilities and fix propositions like this ?
![Screenshot 2024-01-08 at 16 16 05](https://github.com/janus-idp/backstage-plugins/assets/463790/fc4ab2ea-2daa-43e1-bc58-cb4def88f794)
